### ISSUE TITLE
Both error when install using "npm install phantomjs" and "node ./install.js" on mac

### ISSUE THREAD

**Issue by zhaoyingx** [Medium/phantomjs#156]
1) npm install phantomjs

Downloading http://cdn.bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-macosx.zip
Saving to /var/folders/4q/45xt6phn4nz_q02_nchk_c300000gn/T/phantomjs/phantomjs-1.9.7-macosx.zip

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete](net.js:892:19)
npm ERR! phantomjs@1.9.7-5 install: `node install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the phantomjs@1.9.7-5 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "phantomjs"
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! not ok code 0

2) git clone the source code and node ./install.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'adm-zip'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/...../phantomjs/install.js:9:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by kylinsoong** [comment]
I just would append the following error output what I have met:
~~~
$ npm install gitbook-pdf -g
npm WARN deprecated npmconf@0.0.24: this package has been reintegrated into npm and is now out of date with respect to npm
-
> phantomjs@1.9.7-5 install /home/kylin/tools/node-v0.12.6-linux-x64/lib/node_modules/gitbook-pdf/node_modules/phantomjs
> node install.js

Downloading http://cdn.bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.7-linux-x86_64.tar.bz2
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
npm ERR! Linux 3.11.10-301.fc20.x86_64
npm ERR! argv "/home/kylin/tools/node-v0.12.6-linux-x64/bin/node" "/home/kylin/tools/node-v0.12.6-linux-x64/bin/npm" "install" "gitbook-pdf" "-g"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.7-5 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.7-5 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kylin/npm-debug.log
~~~

**Comment by fengmk2** [comment]
@kylinsoong cdn.bitbucket.org was block by GFW in China.

**Comment by humitos** [comment]
I have the same issue than @kylinsoong (trying to install gitbook-pdf). Was you able to solve it?

**Comment by Adrian0350** [comment]
Trying to install `gitbook-pdf` as well threw this error and also when trying to install `phantomjs` by itself.

```
$ sudo npm install phantomjs@1.9.7-5 -g
npm WARN deprecated npmconf@0.0.24: this package has been reintegrated into npm and is now out of date with respect to npm
/opt/local/bin/phantomjs -> /opt/local/lib/node_modules/phantomjs/bin/phantomjs

> phantomjs@1.9.7-5 install /opt/local/lib/node_modules/phantomjs
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Downloading http://cdn.bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-macosx.zip
Saving to /opt/local/lib/node_modules/phantomjs/phantomjs/phantomjs-1.9.7-macosx.zip
Receiving...
Error requesting archive.
Status: 301
Request options: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "cdn.bitbucket.org",
  "port": null,
  "hostname": "cdn.bitbucket.org",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/ariya/phantomjs/downloads/phantomjs-1.9.7-macosx.zip",
  "path": "/ariya/phantomjs/downloads/phantomjs-1.9.7-macosx.zip",
  "href": "http://cdn.bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-macosx.zip"
}
Response headers: {
  "content-type": "text/html",
  "content-length": "0",
  "connection": "close",
  "date": "Thu, 12 Apr 2018 16:37:35 GMT",
  "location": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-macosx.zip",
  "age": "341",
  "x-cache": "Hit from cloudfront",
  "via": "1.1 1c5ed0f77034c0df69d10c5f36daea8c.cloudfront.net (CloudFront)",
  "x-amz-cf-id": "fWtxQ-DiRf69D3tjtKHDn6D9kAvhf6XGk1eHcAI5IZZss2hqo6hSKw=="
}
Make sure your network and proxy settings are correct.
npm ERR! Darwin 17.5.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install" "phantomjs@1.9.7-5" "-g"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.7-5 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.7-5 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Desktop/htmltopdf/npm-debug.log
```
