### ISSUE TITLE
phantomjs implicitly requires libfontconfig1.so as a dependency

### ISSUE THREAD

**Issue by olierxleben** [Medium/phantomjs#208]
Hey, 

I tried grunt jasmine and it seems phantomjs has libfontconfig1.so as a dependency. But it wont create the shared object on install (npm install phantomjs e.g.). I tried it on ubuntu but in order to get it working I was needed to apt-get install libfontconfig. Shouldn`t this be a dependency for the package?

**Comment by aressler38** [comment]
I'm also seeing this error. I'm installing karma and karma-qunit behind a proxy server and `npm install` fails when it starts to download phantomjs. I'm able to install other npm packages without issue, so I believe that my proxy settings are configured OK. 

Here is the error log:


> ws@0.4.32 install /vagrant/code/tablet_07172014_fullscreenoverlay/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/vagrant/code/tablet_07172014_fullscreenoverlay/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/vagrant/code/tablet_07172014_fullscreenoverlay/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
\
> phantomjs@1.9.13 install /vagrant/code/tablet_07172014_fullscreenoverlay/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Using proxy https://aressler:******@iadwg-lb.corp.etradegrp.com:9090/
Receiving...

Error making request.
Error: tunneling socket could not be established, cause=140478762870656:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:795:

    at ClientRequest.onError (/vagrant/code/tablet_07172014_fullscreenoverlay/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/node_modules/request/node_modules/tunnel-agent/index.js:168:17)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1552:9)
    at CleartextStream.emit (events.js:95:17)
    at SecurePair.<anonymous> (tls.js:1411:15)
    at SecurePair.emit (events.js:95:17)
    at SecurePair.error (tls.js:1018:27)
    at CleartextStream.read [as _read] (tls.js:463:17)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)

Please report this full log at https://github.com/Medium/phantomjs

npm ERR! phantomjs@1.9.13 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.13 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /vagrant/code/tablet_07172014_fullscreenoverlay
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by Splaktar** [comment]
Yep, on Ubuntu server cloud instances, running PhantomJS always fails until I do `apt-get install libfontconfig`.

**Comment by vmadman** [comment]
fyi, for CentOS 7 (and probably newer versions):

```
yum install urw-fonts -y
```

See: https://github.com/vmadman/linux-scripts/blob/master/vagrant/centos7/dev/v1/yum-install-fonts.sh
