### ISSUE TITLE
Error on webpage.open with base href and unexisting resource

### ISSUE THREAD

**Issue by timmipetit** [Medium/phantomjs#239]
We have encountered a problem when using`webpage.open()` on a HTML-file that contains a `<base href>` and some resource (for example, an `<img>`) that can not be found. This problem only occurs when our webserver calls the phantomjs executable. Using a standalone Phantomjs binary also works fine.

**Example**:
input.hml:

``` html
<html>
  <head>
    <base href="http://some.host/" />
  </head>
<body>
<img src="images/doesNotExist.png" />
</body>cp
</html>
```

open.js:

``` javascript
var page = require('webpage').create();

function errorHandler(e) {
    console.log(JSON.stringify({
        success: false,
        response: e.toString()
    }));

    // Stop the script
    phantom.exit(0);
}

try {
    console.log('trying to open the file');
    page.open('/path/to/input.html', function (status) {
        try {
            console.log('opened the file!');
            if (status !== 'success') {
                throw 'Unable to access the URI!';
            }

            phantom.exit(0);

        } catch (e) {
            errorHandler(e);
        }
    });
} catch (e) {
    errorHandler(e);
}
```

exec.php:

``` php
<?php
exec('phantomjs /path/to/open.js > ~/debug.log 2>&1');
```

If we execute `php exec.php` from the command line, everything works as expected. If we open exec.php in the browser, debug.log contains:

```
trying to open the file

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read EINVAL
    at errnoException (net.js:904:11)
    at Pipe.onread (net.js:558:19)
```

If we remove the `<base href>` from the HTML, everything works. Also, if the resource does exist, everything also works as expected. Using the standalone Phantomjs version (instead of the nodejs wrapper) also works fine.

Used software:
phantomjs 1.9.7
php 5.3.10
nginx 1.1.19 php-fpm

We first openend this issue on the Phantomjs repo (https://github.com/ariya/phantomjs/issues/12653)

**Comment by jeff1985** [comment]
same here!
phantomjs 2.1.1
ubuntu 16.04
php 7.0.18
 and php-fpm

**Comment by orditeck** [comment]
@jeff1985 I had the same issue, your workaround worked perfectly. Thanks for adding it to your comment.
