### ISSUE TITLE
PhantomJS detected, but wrong version 1.9.7

### ISSUE THREAD

**Issue by shabfactor** [Medium/phantomjs#250]
```
   > phantomjs@1.9.12 install /repository/jenkins/jobs/styleguide_build_deploy/workspace 
   /node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs
   > node install.js

 PhantomJS detected, but wrong version 1.9.7 @    
/usr/local/bin/phantomjs.
 Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-
 1.9.8-linux-x86_64.tar.bz2
 Saving to /var/lib/jenkins/tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
 Using proxy http://www-proxy.niwa.co.nz:80/
 Receiving...

Error making request.
Error: CERT_UNTRUSTED
 at SecurePair.<anonymous> (tls.js:1357:32)
 at SecurePair.EventEmitter.emit (events.js:92:17)
 at SecurePair.maybeInitFinished (tls.js:970:10)
 at CleartextStream.read [as _read] (tls.js:463:15)
 at CleartextStream.Readable.read (_stream_readable.js:320:10)
 at EncryptedStream.write [as _write] (tls.js:366:25)
 at doWrite (_stream_writable.js:219:10)
 at writeOrBuffer (_stream_writable.js:209:5)
 at EncryptedStream.Writable.write (_stream_writable.js:180:11)
 at write (_stream_readable.js:583:24)

 Please report this full log at https://github.com/Medium/phantomjs
 npm ERR! weird error 1
 npm ERR! not ok code 0
```

Have no idea what is going on,getting this error when trying to run the npm install on server.i don't know what changed in lat few hours on github

**Comment by Deepakdubey90** [comment]
Hi, guys i getting error during UI unit test case(karma-phantomJs-launcher,  jasmine).
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
Some of your tests did a full page reload!  (error)
PhantomJS 1.9.8 (Linux 0.0.0): Executed 51 of 97 ERROR (0.23 secs / 0.221 secs)

not executing all the app.
please suggest me to fix this issue.

**Comment by VikrantGodse** [comment]
Hey m also getting same error.....

**Comment by maruthi1255** [comment]
Hi,
Do any one know why are we getting this error and what is the fix for this?
