### ISSUE TITLE
1.9.14 breaks on Linux when installing in local directory

### ISSUE THREAD

**Issue by chrylis** [Medium/phantomjs#280]
I am getting reliable failures with the 1.9.14 release when running `npm install` without a system-wide `phantomjs` binary. It looks like an expected path got fat-fingered.

````
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1422372975393/phantomjs-1.9.8-linux-x86_64 -> /home/christopher/git/caniprintit/caniprintit-resources/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Writing location.js file
Phantom installation failed { [Error: ENOTDIR, not a directory '/home/christopher/git/caniprintit/caniprintit-resources/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs']
  errno: 27,
  code: 'ENOTDIR',
  path: '/home/christopher/git/caniprintit/caniprintit-resources/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs',
  syscall: 'chmod' } Error: ENOTDIR, not a directory '/home/christopher/git/caniprintit/caniprintit-resources/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs'
    at Object.fs.chmodSync (evalmachine.<anonymous>:833:18)
    at Object.chmodSync (/home/christopher/git/caniprintit/caniprintit-resources/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/node_modules/fs-extra/node_modules/graceful-fs/polyfills.js:141:17)
    at Promise.validExit [as _successFn] (/home/christopher/git/caniprintit/caniprintit-resources/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/install.js:145:8)
    at Promise._call (/home/christopher/git/caniprintit/caniprintit-resources/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/node_modules/kew/kew.js:373:13)
    at Promise._withInput (/home/christopher/git/caniprintit/caniprintit-resources/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/node_modules/kew/kew.js:333:25)
    at Promise.resolve (/home/christopher/git/caniprintit/caniprintit-resources/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/node_modules/kew/kew.js:105:27)
    at resolver (/home/christopher/git/caniprintit/caniprintit-resources/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/node_modules/kew/kew.js:409:17)
    at CB (/home/christopher/git/caniprintit/caniprintit-resources/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/node_modules/fs-extra/node_modules/rimraf/rimraf.js:68:5)
    at Object.oncomplete (fs.js:108:15)

npm ERR! phantomjs@1.9.14 install: `node install.js`
npm ERR! Exit status 1
````

**Comment by chrylis** [comment]
Confirmed that pinning the dependency to 1.9.13 makes the problem go away on both dev and CI.

**Comment by nicks** [comment]
dupe #279
