### ISSUE TITLE
npm install fails on windows

### ISSUE THREAD

**Issue by sergioharo** [Medium/phantomjs#284]
Our current build process (on windows) is failing on version 1.9.15. The last successful build used 1.9.13. We get the following stack trace:

> phantomjs@1.9.15 install d:\builds\jenkins\workspace\js\unit-tests\node_modules\karma-phantomjs-launcher\node_modules\phantomjs
> node install.js

Download already available at C:\Users\tempuser\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Extracting zip contents
Phantom installation failed [Error: Can't move source into dest if dest is in source.] Error: Can't move source into dest if dest is in source.
    at mv (d:\builds\jenkins\workspace\js\unit-tests\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\fs-extra\lib\move.js:22:15)
    at fs.move (d:\builds\jenkins\workspace\js\unit-tests\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\fs-extra\lib\index.js:51:3)
    at onBoundPromise (d:\builds\jenkins\workspace\js\unit-tests\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\kew\kew.js:703:10)
    at Object.nfcall (d:\builds\jenkins\workspace\js\unit-tests\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\kew\kew.js:685:44)
    at Promise._successFn (d:\builds\jenkins\workspace\js\unit-tests\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\install.js:341:20)
    at Promise._call (d:\builds\jenkins\workspace\js\unit-tests\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\kew\kew.js:373:13)
    at Promise._withInput (d:\builds\jenkins\workspace\js\unit-tests\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\kew\kew.js:333:25)
    at Promise.resolve (d:\builds\jenkins\workspace\js\unit-tests\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\kew\kew.js:105:27)
    at resolver (d:\builds\jenkins\workspace\js\unit-tests\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\kew\kew.js:409:17)
    at CB (d:\builds\jenkins\workspace\js\unit-tests\node_modules\rimraf\rimraf.js:68:5)
npm ERR! phantomjs@1.9.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.15 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--loglevel" "warn"
npm ERR! cwd d:\builds\jenkins\workspace\js\unit-tests
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npmBuild step 'Conditional steps (multiple)' marked build as failure

Our package.json includes the following dependencies:
{
    "karma": "^0.12.1",
    "karma-jasmine": "^0.2.2",
    "karma-requirejs": "^0.2.1",
    "karma-phantomjs-launcher": "^0.1.2",
    "karma-chrome-launcher": "^0.1.3",
    "karma-coverage": "^0.2.1",
    "karma-ng-html2js-preprocessor": "^0.1.0",
    "karma-junit-reporter": "^0.2.2",
    "rimraf": "^2.2.8"
  } 

Adding 1.9.13 to the dependencies fixes our build

**Comment by nicks** [comment]
is that the full error log? It's conspicuously missing some important information.

**Comment by sergioharo** [comment]
Thats what shows up in our jenkins log. If you're looking for something specific, let me know and I can look around for it or turn up the log level. Its currently set to warn on npm.

**Comment by admiller97** [comment]
I'm also getting the issue now

**Comment by nicks** [comment]
we need the logs on what it's trying to copy where. Those logs show up for me; I don't know where they're getting eaten in your pipeline.

**Comment by admiller97** [comment]
> phantomjs@1.9.15 install D:\Apps\ContentDirect\Consumer\HTML\Build\node_modules\phantomjs
> node install.js

Download already available at C:\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Extracting zip contents
Removing D:\Apps\ContentDirect\Consumer\HTML\Build\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1422477496915\phantomjs-1.9.8-windows -> D:\Apps\ContentDirect\Consumer\HTML\Build\node_modules\phant
omjs\lib\phantom
Phantom installation failed [Error: Can't move source into dest if dest is in source.] Error: Can't move source into dest if dest is in source.
    at mv (D:\Apps\ContentDirect\Consumer\HTML\Build\node_modules\phantomjs\node_modules\fs-extra\lib\move.js:22:15)
    at fs.move (D:\Apps\ContentDirect\Consumer\HTML\Build\node_modules\phantomjs\node_modules\fs-extra\lib\index.js:51:3)
    at onBoundPromise (D:\Apps\ContentDirect\Consumer\HTML\Build\node_modules\phantomjs\node_modules\kew\kew.js:703:10)
    at Object.nfcall (D:\Apps\ContentDirect\Consumer\HTML\Build\node_modules\phantomjs\node_modules\kew\kew.js:685:44)
    at Promise._successFn (D:\Apps\ContentDirect\Consumer\HTML\Build\node_modules\phantomjs\install.js:341:20)
    at Promise._call (D:\Apps\ContentDirect\Consumer\HTML\Build\node_modules\phantomjs\node_modules\kew\kew.js:373:13)
    at Promise._withInput (D:\Apps\ContentDirect\Consumer\HTML\Build\node_modules\phantomjs\node_modules\kew\kew.js:333:25)
    at Promise.resolve (D:\Apps\ContentDirect\Consumer\HTML\Build\node_modules\phantomjs\node_modules\kew\kew.js:105:27)
    at resolver (D:\Apps\ContentDirect\Consumer\HTML\Build\node_modules\phantomjs\node_modules\kew\kew.js:409:17)
    at CB (D:\Apps\ContentDirect\Consumer\HTML\Build\node_modules\phantomjs\node_modules\fs-extra\node_modules\rimraf\rimraf.js:68:5)
npm ERR! phantomjs@1.9.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.15 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\ProgramData\\chocolatey\\lib\\nodist.0.4.6-beta\\tools\\nodist-master/v/0.10.33/node.exe" "C:\\ProgramData\\chocolatey\\lib\\nodist.0.4.6-beta\\tools\\nodist-
master\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install" "phantomjs"
npm ERR! cwd D:\Apps\ContentDirect\Consumer\HTML\Build
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.6
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\Apps\ContentDirect\Consumer\HTML\Build\npm-debug.log
npm ERR! not ok code 0

**Comment by admiller97** [comment]
Here's a link to npm-debug.log https://dl.dropboxusercontent.com/u/1037491/npm-debug.log

**Comment by nicks** [comment]
thanks, i filed this as https://github.com/jprichardson/node-fs-extra/issues/109

**Comment by nicks** [comment]
for now, I think you can work around this by setting the TEMP environment variable to a directory on the same drive as your install directory

**Comment by sergioharo** [comment]
cool, thanks!

**Comment by jprichardson** [comment]
@sergioharo Can you try again? The `phantomjs` will now use the latest `fs-extra@0.16.3`.

**Comment by admiller97** [comment]
seems to have fixed it for me.  Thanks for the quick turn around.

**Comment by nicks** [comment]
ya, @jprichardson is pretty fast :zap: :zap: :zap: . thanks all.

**Comment by sergioharo** [comment]
Yep, fixed for me too

**Comment by prettycode** [comment]
What version of phantomjs node package do I need to use to get the version that uses `fs-extra@0.16.3`?

**Comment by jprichardson** [comment]
fs-extra author here. Have you verified that 0.16.3 works and that 0.16.5
does not?

On Saturday, March 21, 2015, Chris <notifications@github.com> wrote:

> What version of phantomjs node package do I need to use to get the version
> that uses fs-extra@0.16.3?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Medium/phantomjs/issues/284#issuecomment-84276993>.
>


-- 
Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
Bitcoin / JavaScript: http://cryptocoinjs.com
Follow JP Richardson on Twitter: https://twitter.com/jprichardson

**Comment by jprichardson** [comment]
Also, if you could verify 0.16.4. I could then revert the offending patches
and publish 0.16.6.

On Saturday, March 21, 2015, JP Richardson <jprichardson@gmail.com> wrote:

> fs-extra author here. Have you verified that 0.16.3 works and that 0.16.5
> does not?
>
> On Saturday, March 21, 2015, Chris <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> What version of phantomjs node package do I need to use to get the
>> version that uses fs-extra@0.16.3?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Medium/phantomjs/issues/284#issuecomment-84276993>.
>>
>
>
> --
> Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
> Bitcoin / JavaScript: http://cryptocoinjs.com
> Follow JP Richardson on Twitter: https://twitter.com/jprichardson
>
>
>

-- 
Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
Bitcoin / JavaScript: http://cryptocoinjs.com
Follow JP Richardson on Twitter: https://twitter.com/jprichardson

**Comment by prettycode** [comment]
@jprichardson Actually, this issue appears to better capture what I'm experiencing: 

https://github.com/Medium/phantomjs/issues/297

It's hard to reproduce. Happens about 1/5 installs. It's running on our build server and randomly, what's shown in that issued I linked, happens. We've been using 1.9.15 the whole time, so couldn't tell you about other versions.

Sorry to cause alarm. There's definitely a problem, but have no idea about fs-extra's dependency being involved.
