### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by Kertis** [Medium/phantomjs#285]
Can't install phantomjs on my ubuntu machine using npm.
```
npm install phantomjs
```
output:
```
npm WARN package.json nodejs@0.0.0 No repository field.
\
> phantomjs@1.9.15 install /root/WebstormProjects/AngularProject/node_modules/phantomjs
> node install.js

module.js:338
    throw err;
          ^
Error: Cannot find module '/root/WebstormProjects/AngularProject/node_modules/phantomjs/install.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Linux 3.16.0-29-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "phantomjs"
npm ERR! node v0.11.15
npm ERR! npm  v2.1.6
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.15 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/WebstormProjects/AngularProject/npm-debug.log
```
Full log: http://paste.ubuntu.com/9926286/

**Comment by nicks** [comment]
that log looks like npm corrupted the package, have you tried running an `npm cache clean`?

**Comment by Kertis** [comment]
Yes

**Comment by nicks** [comment]
based on the log, npm is failing before it even gets to the phantomjs code, so I'm not sure if there's anything we can do to help you. The only thing I can think of is that you have npm, node, or the NODE_PATH env variable misconfigured.

**Comment by Kertis** [comment]
Are you pretty sure that problem is in npm? As for me, it is unclear how it could be misconfigured if I done the fresh install. Because, the only thing that I did was 
```
sudo apt-get install nodejs
```

**Comment by nicks** [comment]
`Error: Cannot find module '/root/WebstormProjects/AngularProject/node_modules/phantomjs/install.js'`
means that node wasn't able to find where it put the phantomjs code

**Comment by sranger** [comment]
Similar issue. Installing phantomjs on a ubuntu 14.10 VM, using --no-bin-links as it's being stored inside a shared drive that my windows machine can also access.

```
npm WARN package.json AFRLMPC@0.0.0 No repository field.
/
> phantomjs@1.9.15 install /media/sf_dev/mpc/code/web/node_modules/phantomjs
> node install.js


module.js:340
    throw err;
          ^
Error: Cannot find module '/media/sf_dev/mpc/code/web/node_modules/phantomjs/install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! phantomjs@1.9.15 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.15 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links" "phantomjs"
npm ERR! cwd /media/sf_dev/mpc/code/web
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /media/sf_dev/mpc/code/web/npm-debug.log
npm ERR! not ok code 0
```

and the log is too long to paste and github only supports attaching images; if you'd like it, I've saved it.

**Comment by nicks** [comment]
I am closing this bug because there is no further action we can take on this. NPM is failing before it even gets to the phantomjs installer.
