### ISSUE TITLE
npm install failure after 1.9.15 on Windows 2008 Server

### ISSUE THREAD

**Issue by charsoxer** [Medium/phantomjs#286]
As stated in title, after 1.9.15 was released our npm install began to fail on our windows 2008 box. Everything is still working fine locally on windows 7 machines.

We noticed that yo have updated your fs library to fs-extra which is where we are failing on. However, we have no idea why. Let me know if you need any more information.

Thanks!

```
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to C:\Users\APPSDINNOV01\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...

Received 7292K total.
Phantom installation failed [Error: Can't move source into dest if dest is in source.] Error: Can't move source into dest if dest is in source.
    at mv (D:\Jenkins\jobs\obsc-login-app\workspace\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\fs-extra\lib\move.js:22:15)
    at fs.move (D:\Jenkins\jobs\obsc-login-app\workspace\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\fs-extra\lib\index.js:51:3)
    at onBoundPromise (D:\Jenkins\jobs\obsc-login-app\workspace\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\kew\kew.js:703:10)
    at Object.nfcall (D:\Jenkins\jobs\obsc-login-app\workspace\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\kew\kew.js:685:44)
    at Promise._successFn (D:\Jenkins\jobs\obsc-login-app\workspace\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\install.js:341:20)
    at Promise._call (D:\Jenkins\jobs\obsc-login-app\workspace\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\kew\kew.js:373:13)
    at Promise._withInput (D:\Jenkins\jobs\obsc-login-app\workspace\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\kew\kew.js:333:25)
    at Promise.resolve (D:\Jenkins\jobs\obsc-login-app\workspace\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\kew\kew.js:105:27)
    at resolver (D:\Jenkins\jobs\obsc-login-app\workspace\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\kew\kew.js:409:17)
    at CB (D:\Jenkins\jobs\obsc-login-app\workspace\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\fs-extra\node_modules\rimraf\rimraf.js:68:5)
npm ERR! phantomjs@1.9.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.15 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\Jenkins\jobs\obsc-login-app\workspace
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
```

**Comment by nicks** [comment]
you need to do a clean install to pull in the fs-extra patch updates. dupe #284
