### ISSUE TITLE
Certificate untrusted

### ISSUE THREAD

**Issue by schalkneethling** [Medium/phantomjs#291]
PhantomJS detected, but wrong version 1.9.2 @ /usr/local/bin/phantomjs.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-macosx.zip
Saving to /var/folders/fq/80yxw6xx6qn3sly1_x_hmvxr0000gp/T/phantomjs/phantomjs-1.9.7-macosx.zip
Receiving...
Error making request.
Error: CERT_UNTRUSTED
    at SecurePair.<anonymous> (tls.js:1381:32)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:980:10)
    at CleartextStream.read [as _read] (tls.js:472:13)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)

**Comment by nicks** [comment]
This means you've got a bogus proxy (in which case you need to fix your proxy), or you've got a version of nodejs with a broken ssl implementation (see #262)
