### ISSUE TITLE
npm breaks module-loading during the install phase

### ISSUE THREAD

**Issue by nicks** [Medium/phantomjs#302]
This is a tracking bug for problems that we've seen where node module-loading does not work during NPM's install phase. Users typically get an error that looks like:

```
phantomjs@1.9.15 install C:\Users\name\AppData\Roaming\npm\node_modules\phantomjs
node install.js
module.js:340
throw err;
^
Error: Cannot find module 'C:\Users\name\Documents\install.js'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:906:3
```

We're pretty confident that this is an NPM bug, or caused by some misconfiguration of the environment (NPM pulls a lot of random stuff from the environment). We probably can't workaround this in the phantomjs installer even if we wanted to, because it's not even able to open the phantomjs installer code.

**Comment by nicks** [comment]
(We currently do not have repro steps for this, but people who see it claim they can repro it consistently)

**Comment by nicks** [comment]
(The next steps on this bug is that someone who can reproduce it needs to step through what npm/node is doing, why is can't load modules in this mode, and file an appropriate bug against npm/node)

**Comment by UltimateFighter** [comment]
319 is not the same problem, because: "Error: Cannot find module 'c:\install.js'". Here is the missing path ever "c:\install.js"

**Comment by nicks** [comment]
The bug is that npm is not able to load the phantomjs installer code. The directory name is interesting, and possibly a clue. But either way, it doesn't seem likely that we can do much about this on the phantomjs side if our code isn't running yet.

**Comment by UltimateFighter** [comment]
But Phantomjs is the only one dependency from a lot of we using in our Module Directory. All other libs  are loadded successfully. Perhaps it's a but in the phantomjs Script or in the installer?

**Comment by liam-swinney** [comment]
Hi guys, not sure if this is any help but we are getting this issue randomly as well,  we run it on TeamCity on a windows agent and have phantomjs installed globally.   We cannot recreate this bug locally and as I say it randomly fails (then passes when we retry) and get this response:

```html
[11:10:51][Step 3/12] > phantomjs@1.9.16 install C:\BuildAgent2\work\7ea1530d04a43808\src\FrontendBuildTasks\node_modules\karma-phantomjs-launcher\node_modules\phantomjs
[11:10:51][Step 3/12] > node install.js
[11:10:51][Step 3/12] Looks like an `npm install -g` on windows; unable to check for already installed version.
[11:10:51][Step 3/12] Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
[11:10:52][Step 3/12] Saving to C:\BuildAgent2\temp\buildTmp\phantomjs\phantomjs-1.9.8-windows.zip
[11:10:52][Step 3/12] Receiving...

[11:11:01][Step 3/12] Received 7292K total.
[11:11:01][Step 3/12] Extracting zip contents
[11:11:01][Step 3/12] Removing E:\Agent 02\work\7ea1530d04a43808\src\FrontendBuildTasks\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom
[11:11:01][Step 3/12] Copying extracted folder C:\BuildAgent2\temp\buildTmp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1427368259546\phantomjs-1.9.8-windows -> E:\Agent 02\work\7ea1530d04a43808\src\FrontendBuildTasks\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom


[11:11:05][Step 3/12] npm ERR! phantomjs@1.9.16 install: `node install.js`
[11:11:05][Step 3/12] npm ERR! Exit status 1
[11:11:05][Step 3/12] npm ERR! 
[11:11:05][Step 3/12] npm ERR! Failed at the phantomjs@1.9.16 install script.
[11:11:05][Step 3/12] npm ERR! This is most likely a problem with the phantomjs package,
[11:11:05][Step 3/12] npm ERR! not with npm itself.
[11:11:05][Step 3/12] npm ERR! Tell the author that this fails on your system:
[11:11:05][Step 3/12] npm ERR!     node install.js
[11:11:05][Step 3/12] npm ERR! You can get their info via:
[11:11:05][Step 3/12] npm ERR!     npm owner ls phantomjs
[11:11:05][Step 3/12] npm ERR! There is likely additional logging output above.
[11:11:05][Step 3/12] 
[11:11:05][Step 3/12] npm ERR! System Windows_NT 6.1.7601
[11:11:05][Step 3/12] npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
[11:11:05][Step 3/12] npm ERR! cwd C:\BuildAgent2\work\7ea1530d04a43808\src\FrontendBuildTasks
[11:11:05][Step 3/12] npm ERR! node -v v0.10.24
[11:11:05][Step 3/12] npm ERR! npm -v 1.3.21
[11:11:05][Step 3/12] npm ERR! code ELIFECYCLE
```

Hope it helps!

**Comment by phpguru** [comment]
Really strange. I've arrived here with a phantomjs issue also, running npm install or npm update...

```
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /src/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
  [===================================-----] 88% 0.0s
Received 12854K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { [Error: Command failed: tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
] killed: false, code: 2, signal: null } Error: Command failed: tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.16 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.18.5-tinycore64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /src
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```
It looks as if the installer tries to continue before downloading is complete? I've tried it a few times and it has gotten beyond 81%, 86%, 88% in this example. I'm not sure if this helps. I tried running in --verbose mode but the output surrounding phantomjs install failure are unaffected.

**Comment by nicks** [comment]
@phpguru this is an unrelated issue. you need to install bzip2

**Comment by phpguru** [comment]
@nicks Thanks for the info! I am building phantomjs from source inside a docker container. It's taking forever.

**Comment by lokeshjainRL** [comment]
Just to help you guys.

```

sudo npm install
Password:

> phantomjs@1.9.16 install /Users/Lokesh/Documents/ReachSign-client/node_modules/phantomjs
> node install.js


module.js:340
    throw err;
          ^
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Lokesh/Documents/ReachSign-client/node_modules/phantomjs/node_modules/fs-extra/node_modules/rimraf/rimraf.js:7:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.16 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.3.0
npm ERR! command "/usr/local/opt/nvm/v0.10.38/bin/node" "/usr/local/opt/nvm/v0.10.38/bin/npm" "install"
npm ERR! cwd /Users/Lokesh/Documents/ReachSign-client
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Lokesh/Documents/ReachSign-client/npm-debug.log
npm ERR! not ok code 0

```

**Comment by Gorgia666** [comment]
this saved my day:
http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu

> sudo apt-get install nodejs-legacy

**Comment by StTheo** [comment]
I've been having the same issue for about a day on my Windows machine. I must have uninstalled/reinstalled node.js about a dozen times by now trying to get around this bug. I should also point out that this is the only module that behaves this way out of the several dozen I have to install, so my personal opinion is that this isn't npm's fault.

**Comment by nicks** [comment]
@StTheo if you believe you know what the problem is, feel free to send a PR to fix.

**Comment by LeviTaule** [comment]
I had had the exactly same issue here on Linux using the newest stable NPM and phantomjs builds twice. before *reading EmberJS docs* and then trying to install it again. Funny thing - the last time it worked. And I don't know why. I've done nothing but read the docs.

**Comment by israelsapir** [comment]
Download & Install new node js version

**Comment by anhnhoktvn** [comment]
Just another fail

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm ERR! Linux 4.4.5-1-MANJARO
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.0
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.5 install: `node install.js`
npm ERR! Exit status 1

**Comment by giorgiosironi** [comment]
Same problem running `npm install`:
```
...
15:43:01 > phantomjs-prebuilt@2.1.7 install /var/lib/jenkins-libraries-runner/workspace/library-pattern-library/node_modules/phantomjs-prebuilt
15:43:01 > node install.js
```
Exit code 1. When I raise the log level to `silly` to get more output, the error seems to vanish.

**Comment by giorgiosironi** [comment]
Interestingly, running `node ./install.js` on a local machine works, while on this EC2 instance;
```
$ node ./install.js
PhantomJS not found on PATH
Phantom installation failed TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
      at Object.join (path.js:1213:7)
      at findSuitableTempDirectory (/var/lib/jenkins-libraries-runner/workspace/library-pattern-library/node_modules/phantomjs-prebuilt/install.js:127:30)
      at /var/lib/jenkins-libraries-runner/workspace/library-pattern-library/node_modules/phantomjs-prebuilt/install.js:476:19
          at nextTickCallback (/var/lib/jenkins-libraries-runner/workspace/library-pattern-library/node_modules/kew/kew.js:47:28)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9) TypeError: Path must be a string. Received undefined
          at assertPath (path.js:7:11)
      at Object.join (path.js:1213:7)
      at findSuitableTempDirectory (/var/lib/jenkins-libraries-runner/workspace/library-pattern-library/node_modules/phantomjs-prebuilt/install.js:127:30)
      at /var/lib/jenkins-libraries-runner/workspace/library-pattern-library/node_modules/phantomjs-prebuilt/install.js:476:19
          at nextTickCallback (/var/lib/jenkins-libraries-runner/workspace/library-pattern-library/node_modules/kew/kew.js:47:28)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by giorgiosironi** [comment]
Apparently all 3 options at this line:
https://github.com/Medium/phantomjs/blob/master/install.js#L107
are `undefined`. It could be the version of node, which is `v6.2.1`.

**Comment by giorgiosironi** [comment]
This is something that has to do with the current user in my case, because in the working machine the first option becomes `/tmp/user/1001` while in the second case I am executing the build as a system user (`jenkins`) and it may have a different environment.

**Comment by giorgiosironi** [comment]
Someone proposed a quick fix for this problem, which may be the source of this issue: https://github.com/Medium/phantomjs/pull/536

**Comment by giorgiosironi** [comment]
Once solved the temporary variable, I found out another problem was not enough RAM available. The `npm-debug.log` is seldom being written in this cases, so watch out for that, especially in CI where there is the added overhead of an agent.

**Comment by Mauricio3000** [comment]
Had this issue on CentOS 7 Docker container.

My problem was that I was missing tar and bzip2

Once I installed them, no more errors.
