### ISSUE TITLE
PhanomJS package can't be installed

### ISSUE THREAD

**Issue by CullenShane** [Medium/phantomjs#310]
Our CI server is suddenly unable to install PhantomJS using this package.  Going to the page download link manually is a 403 Forbidden.

In addition, the download link in the README also results in a 403 Forbidden. 

> Try visiting the the [download page manually](http://cdn.bitbucket.org/ariya/phantomjs/downloads). If that page is blocked, you can try using a different CDN with the PHANTOMJS_CDNURL env variable described above.

```
$ phantomjs@1.9.7-1 install /home/ubuntu/apruve/node_modules/phantomjs
$ node install.js
PhantomJS detected, but wrong version 1.9.8 @ /usr/local/bin/phantomjs.
Downloading http://cdn.bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.7-linux-x86_64.tar.bz2
Receiving...
Error requesting archive
Phantom installation failed [Error: Error with http request: { 'content-type': 'text/html',
  'content-length': '14134',
  connection: 'keep-alive',
  date: 'Fri, 06 Mar 2015 02:02:23 GMT',
  'last-modified': 'Sat, 24 May 2014 00:08:24 GMT',
  etag: '"999f4f548bfffe25245dc29e49c57e9c"',
  'accept-ranges': 'bytes',
  server: 'AmazonS3',
  age: '86187',
  'x-cache': 'Error from cloudfront',
  via: '1.1 3572de112011f1b625bb77410b0c5cca.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'qRle9zF7tiX5b248Fr-xMzilvUOZI7Zus3ek3T4FBnU8XHulLD9guA==' }] Error: Error with http request: { 'content-type': 'text/html',
  'content-length': '14134',
  connection: 'keep-alive',
  date: 'Fri, 06 Mar 2015 02:02:23 GMT',
  'last-modified': 'Sat, 24 May 2014 00:08:24 GMT',
  etag: '"999f4f548bfffe25245dc29e49c57e9c"',
  'accept-ranges': 'bytes',
  server: 'AmazonS3',
  age: '86187',
  'x-cache': 'Error from cloudfront',
  via: '1.1 3572de112011f1b625bb77410b0c5cca.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'qRle9zF7tiX5b248Fr-xMzilvUOZI7Zus3ek3T4FBnU8XHulLD9guA==' }
    at ClientRequest.<anonymous> (/home/ubuntu/apruve/node_modules/phantomjs/install.js:227:23)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1692:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socketOnData [as ondata] (http.js:1587:20)
    at TCP.onread (net.js:527:27)
npm ERR! Linux 3.14.28-031428-generic
npm ERR! argv "node" "/home/ubuntu/nvm/v0.10.33/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.16
npm ERR! code ELIFECYCLE
npm ERR! phantomjs@1.9.7-1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.7-1 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/apruve/npm-debug.log

npm install returned exit code 1

```

**Comment by nicks** [comment]
Yeah, sadly, this URL doesn't work anymore. You'll need to update your version of the installer.
