### ISSUE TITLE
i report the full log here as it said

### ISSUE THREAD

**Issue by yanlijun** [Medium/phantomjs#316]
D:\grunttest>npm install
/

> phantomjs@1.9.16 install D:\grunttest\node_modules\grunt-contrib-qunit\node_mo
dules\grunt-lib-phantomjs\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-wind
ows.zip
Saving to C:\Users\ZHANGX~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows
.zip
Receiving...
-
Error making request.
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN engine xmlbuilder@2.4.6: wanted: {"node":"0.8.x || 0.10.x || 0.11.x  ||
 1.0.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\grunttest\npm-debug.log

**Comment by yanlijun** [comment]
Error: connect ETIMEDOUT

sorry for not open the vpn
