### ISSUE TITLE
cannot install markdown-pdf

### ISSUE THREAD

**Issue by brunojacquelin** [Medium/phantomjs#322]
Installing “markdown-pdf@1.3.5” failed.Hide output…

> phantomjs@1.9.16 install C:\Users\JACQUE~1\AppData\Local\Temp\apm-install-dir-115226-9176-1ig25zt\node_modules\markdown-pdf\node_modules\html-pdf\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to C:\Users\JACQUE~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...

Error making request.
Error: connect ETIMEDOUT
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Jacquelin\\AppData\\Local\\atom\\app-0.188.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\Jacquelin\\AppData\\Local\\atom\\app-0.188.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Jacquelin\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Jacquelin\\.atom\\.apmrc" "install" "C:\\Users\\JACQUE~1\\AppData\\Local\\Temp\\d-115226-9176-ryknrq\\package.tgz" "--target=0.21.0" "--arch=ia32" "--msvs_version=2012"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

**Comment by brunojacquelin** [comment]
Meh, sorry... Problem solved by stubbornness.
