### ISSUE TITLE
Installing phantomjs@1.9.16 fails on TeamCity

### ISSUE THREAD

**Issue by liam-swinney** [Medium/phantomjs#325]
Hey,

We are getting an issue when installing PhantomJS on our TeamCity agents.  ' Failed at the phantomjs@1.9.16 install script.'

This issue has been around for a while and we've been able to manage it by re running the build but now it is getting more frequent with about 4 fails to 1 success.  

We have windows agents with PhantomJS installed globally, we clear the node modules on every build and runs the 'npm install' on every build.  (I cannot understand why it is installed globally but it still needs to be downloaded) 

We've tried to debug this locally but cannot as it is successful everytime, the only thing I can do is provide the error response:

```html
[11:10:51][Step 3/12] > phantomjs@1.9.16 install C:\BuildAgent2\work\7ea1530d04a43808\src\FrontendBuildTasks\node_modules\karma-phantomjs-launcher\node_modules\phantomjs
[11:10:51][Step 3/12] > node install.js
[11:10:51][Step 3/12] Looks like an `npm install -g` on windows; unable to check for already installed version.
[11:10:51][Step 3/12] Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
[11:10:52][Step 3/12] Saving to C:\BuildAgent2\temp\buildTmp\phantomjs\phantomjs-1.9.8-windows.zip
[11:10:52][Step 3/12] Receiving...

[11:11:01][Step 3/12] Received 7292K total.
[11:11:01][Step 3/12] Extracting zip contents
[11:11:01][Step 3/12] Removing E:\Agent 02\work\7ea1530d04a43808\src\FrontendBuildTasks\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom
[11:11:01][Step 3/12] Copying extracted folder C:\BuildAgent2\temp\buildTmp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1427368259546\phantomjs-1.9.8-windows -> E:\Agent 02\work\7ea1530d04a43808\src\FrontendBuildTasks\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom


[11:11:05][Step 3/12] npm ERR! phantomjs@1.9.16 install: `node install.js`
[11:11:05][Step 3/12] npm ERR! Exit status 1
[11:11:05][Step 3/12] npm ERR! 
[11:11:05][Step 3/12] npm ERR! Failed at the phantomjs@1.9.16 install script.
[11:11:05][Step 3/12] npm ERR! This is most likely a problem with the phantomjs package,
[11:11:05][Step 3/12] npm ERR! not with npm itself.
[11:11:05][Step 3/12] npm ERR! Tell the author that this fails on your system:
[11:11:05][Step 3/12] npm ERR!     node install.js
[11:11:05][Step 3/12] npm ERR! You can get their info via:
[11:11:05][Step 3/12] npm ERR!     npm owner ls phantomjs
[11:11:05][Step 3/12] npm ERR! There is likely additional logging output above.
[11:11:05][Step 3/12] 
[11:11:05][Step 3/12] npm ERR! System Windows_NT 6.1.7601
[11:11:05][Step 3/12] npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
[11:11:05][Step 3/12] npm ERR! cwd C:\BuildAgent2\work\7ea1530d04a43808\src\FrontendBuildTasks
[11:11:05][Step 3/12] npm ERR! node -v v0.10.24
[11:11:05][Step 3/12] npm ERR! npm -v 1.3.21
[11:11:05][Step 3/12] npm ERR! code ELIFECYCLE
```

Let me know if you need anymore info!

Thanks

Liam

**Comment by nicks** [comment]
it looks like some of the logs are getting swallowed? are you sure this is the full log?

**Comment by liam-swinney** [comment]
@nicks It's not the full log no, I've taken out the 304 get info messages just to make it easier to read

**Comment by liam-swinney** [comment]
@nicks any ideas?

**Comment by nicks** [comment]
I don't have any additional ideas without repro steps. It sounds like you're the only one who can repro it, and only on a particular machine, so I guess your best bet is to start debugging there?

**Comment by liam-swinney** [comment]
yeah we couldn't reproduce it consistently,  looks like it was an issue with the npm version, updated that and we haven't seen the issue since

**Comment by mikelnick** [comment]
I have this issue now 
```
[12:28:04][Step 4/4] Run NPM Install and then Grunt
[12:28:12][Step 4/4] npm WARN optional dep failed, continuing fsevents@0.3.6
[12:28:23][Step 4/4] 
[12:28:23][Step 4/4] > phantomjs@1.9.16 install ...\TeamCity\buildAgent\work\...\node_modules\grunt-contrib-jasmine\node_modules\grunt-lib-phantomjs\node_modules\phantomjs
[12:28:23][Step 4/4] > node install.js
[12:28:23][Step 4/4] 
[12:28:24][Step 4/4] Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
[12:28:24][Step 4/4] Saving to ...\TeamCity\buildAgent\temp\buildTmp\phantomjs\phantomjs-1.9.8-windows.zip
[12:28:24][Step 4/4] Receiving...
[12:28:25][Step 4/4] 
[12:28:25][Step 4/4] Error making request.
[12:28:25][Step 4/4] Error: certificate not trusted
[12:28:25][Step 4/4]     at Error (native)
[12:28:25][Step 4/4]     at TLSSocket.<anonymous> (_tls_wrap.js:927:36)
[12:28:25][Step 4/4]     at TLSSocket.emit (events.js:104:17)
[12:28:25][Step 4/4]     at TLSSocket._finishInit (_tls_wrap.js:458:8)
[12:28:25][Step 4/4] 
[12:28:25][Step 4/4] Please report this full log at https://github.com/Medium/phantomjs
[12:28:39][Step 4/4] npm ERR! Windows_NT 6.3.9600
[12:28:39][Step 4/4] npm ERR! argv "D:\\nodejs\\\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
[12:28:39][Step 4/4] npm ERR! node v0.12.1
[12:28:39][Step 4/4] npm ERR! npm  v2.5.1
[12:28:39][Step 4/4] npm ERR! code ELIFECYCLE
[12:28:39][Step 4/4] 
[12:28:39][Step 4/4] npm ERR! phantomjs@1.9.16 install: `node install.js`
[12:28:39][Step 4/4] npm ERR! Exit status 1
[12:28:39][Step 4/4] npm ERR! 
[12:28:39][Step 4/4] npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
[12:28:39][Step 4/4] npm ERR! This is most likely a problem with the phantomjs package,
[12:28:39][Step 4/4] npm ERR! not with npm itself.
[12:28:39][Step 4/4] npm ERR! Tell the author that this fails on your system:
[12:28:39][Step 4/4] npm ERR!     node install.js
[12:28:39][Step 4/4] npm ERR! You can get their info via:
[12:28:39][Step 4/4] npm ERR!     npm owner ls phantomjs
[12:28:39][Step 4/4] npm ERR! There is likely additional logging output above.
[12:28:39][Step 4/4] 
[12:28:39][Step 4/4] npm ERR! Please include the following file with any support request:
[12:28:39][Step 4/4] npm ERR!     ...\TeamCity\buildAgent\...\npm-debug.log
[12:28:42][Step 4/4]  [31m>>  [39mLocal Npm module "grunt-contrib-jasmine" not found. Is it installed?
[12:28:42][Step 4/4]  [33mWarning: Task "jasmine" not found.  Use --force to continue. [39m
```

**Comment by nicks** [comment]
@mikelnick https://github.com/Medium/phantomjs#i-am-behind-a-corporate-proxy-that-uses-self-signed-ssl-certificates-to-intercept-encrypted-traffic
