### ISSUE TITLE
Installing PhatomJS@1.9.16 fails ENOENT

### ISSUE THREAD

**Issue by pshokeen** [Medium/phantomjs#326]
Im trying to install PhantomJS on a Centos7 VM.
No matter where i download it from, it always fails on "extracting archive"

Node is correctly installed and is on my PATH

```
npm info install phantomjs@1.9.16

> phantomjs@1.9.16 install /usr/local/lib/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /usr/local/lib/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
  [==============================----------] 74% 0.0s
Received 12854K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { [Error: spawn tar ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn tar',
  path: 'tar',
  cmd: 'tar jxf /usr/local/lib/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2' } Error: spawn tar ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
npm verb unsafe-perm in lifecycle false
npm info phantomjs@1.9.16 Failed to exec install script
npm verb unlock done using /root/.npm/_locks/phantomjs-8361f752b05fa405.lock for /usr/local/lib/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
npm verb about to build /usr/local/lib/node_modules/karma-phantomjs-launcher
npm verb unlock done using /root/.npm/_locks/karma-phantomjs-launcher-03c83d623e3bd6c6.lock for /usr/local/lib/node_modules/karma-phantomjs-launcher
npm verb stack Error: phantomjs@1.9.16 install: `node install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
npm verb stack     at EventEmitter.emit (events.js:110:17)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
npm verb stack     at ChildProcess.emit (events.js:110:17)
npm verb stack     at maybeClose (child_process.js:1008:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
npm verb pkgid phantomjs@1.9.16
npm verb cwd /
npm ERR! Linux 3.18.5-tinycore64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "karma-phantomjs-launcher" "--verbose"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild lib/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
npm info preuninstall phantomjs@1.9.16
npm info uninstall phantomjs@1.9.16
npm verb unbuild rmStuff phantomjs@1.9.16 from /usr/local/lib/node_modules
npm verb unbuild rmStuff in /usr/local/lib/node_modules/karma-phantomjs-launcher/node_modules
npm verb gentlyRm verifying that /usr/local is managed by npm
npm verb gentlyRm vacuuming /usr/local/lib/node_modules/karma-phantomjs-launcher/node_modules/.bin/phantomjs up to /usr/local
npm info postuninstall phantomjs@1.9.16
npm verb gentlyRm vacuuming /usr/local/lib/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
npm verb unbuild lib/node_modules/karma-phantomjs-launcher
npm info preuninstall karma-phantomjs-launcher@0.1.4
npm info uninstall karma-phantomjs-launcher@0.1.4
npm verb unbuild rmStuff karma-phantomjs-launcher@0.1.4 from /usr/local/lib/node_modules
npm info postuninstall karma-phantomjs-launcher@0.1.4
npm verb gentlyRm vacuuming /usr/local/lib/node_modules/karma-phantomjs-launcher

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

**Comment by nicks** [comment]
do you have `tar` installed on PATH?

**Comment by pshokeen** [comment]
You know what, it never occurred to me that it would be that. I just spun up a Centos VM from docker repo. 

when i check "tar" i get "no command found".
how do i install that

**Comment by nicks** [comment]
not sure? `yum install tar` maybe?

**Comment by pshokeen** [comment]
Nick, tar exists now and is in the path as well

```
root@33df8920158a iodocs]# tar --version
tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

But i still get the following error
```
[root@33df8920158a iodocs]# npm install phantomjs
-
> phantomjs@1.9.16 install /usr/jenkins/iodocs/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /usr/jenkins/iodocs/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
  [===============================---------] 78% 0.0s
Received 12854K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { [Error: Command failed: tar jxf /usr/jenkins/iodocs/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
]
  killed: false,
  code: 2,
  signal: null,
  cmd: 'tar jxf /usr/jenkins/iodocs/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2' } Error: Command failed: tar jxf /usr/jenkins/iodocs/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
npm ERR! Linux 3.18.5-tinycore64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "phantomjs"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/jenkins/iodocs/npm-debug.log
```

**Comment by nicks** [comment]
You also need bzip2 per the error message

**Comment by fossouo** [comment]
Hello,
You need to install both bzip2 & tar .

Regards
Donald F.

**Comment by Ntobon** [comment]
Thanks @fossouo ,  Fixed by installing bzip2 package
