### ISSUE TITLE
Failed at the phantomjs@1.9.16 ELIFECYCLE

### ISSUE THREAD

**Issue by pshokeen** [Medium/phantomjs#328]
Running this on a Centos 7 VM
tar exists now and is in the path as well

```
root@33df8920158a iodocs]# tar --version
tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
But i still get the following error

```
[root@33df8920158a iodocs]# npm install phantomjs
-
> phantomjs@1.9.16 install /usr/jenkins/iodocs/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /usr/jenkins/iodocs/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
  [===============================---------] 78% 0.0s
Received 12854K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { [Error: Command failed: tar jxf /usr/jenkins/iodocs/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
]
  killed: false,
  code: 2,
  signal: null,
  cmd: 'tar jxf /usr/jenkins/iodocs/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2' } Error: Command failed: tar jxf /usr/jenkins/iodocs/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
npm ERR! Linux 3.18.5-tinycore64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "phantomjs"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/jenkins/iodocs/npm-debug.log
```

**Comment by pshokeen** [comment]
Installing bzip2 fixed the issue.

**Comment by saha-raskonda** [comment]
Same issue on Red Hat Enterprise Linux Server release 7.0 (Maipo)
Installing bzip2-1.0.6-12.el7.x86_64 RPM resolved it.
Thanks
