### ISSUE TITLE
Cannot install with node ./install.js

### ISSUE THREAD

**Issue by yqfang** [Medium/phantomjs#330]
```
node ./install.js 
module.js:338
    throw err;
          ^
Error: Cannot find module 'request-progress'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/mnt/d/develop/git/phantomjs/install.js:9:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

```

**Comment by nicks** [comment]
This is expected. You don't install npm packages this way, you install them with npm.

**Comment by nicks** [comment]
(npm has to ensure that the transitive dependency of this package is installed first. Your error message is just complaining that those dependencies aren't installed.)
