### ISSUE TITLE
Error making request Error: socket hang up

### ISSUE THREAD

**Issue by hoangddt** [Medium/phantomjs#331]
Hi, I'm trying to install phantomjs and got this problem

```sh
  % npm install phantomjs                                                                                        !1841
\
> phantomjs@1.9.16 install /home/hoangddt/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: socket hang up
    at SecurePair.error (tls.js:1011:23)
    at EncryptedStream.CryptoStream._done (tls.js:703:22)
    at CleartextStream.read [as _read] (tls.js:499:24)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.onCryptoStreamFinish (tls.js:304:47)
    at EncryptedStream.g (events.js:180:16)
    at EncryptedStream.emit (events.js:117:20)
    at finishMaybe (_stream_writable.js:360:12)
    at endWritable (_stream_writable.js:367:3)
    at EncryptedStream.Writable.end (_stream_writable.js:345:5)

Please report this full log at https://github.com/Medium/phantomjs

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.16 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-33-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "phantomjs"
npm ERR! cwd /home/hoangddt
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

```

**Comment by nicks** [comment]
this error means that node was not able to connect to the download server, either because your connection is flakey or someone is blocking access. See:
https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout
for more troubleshooting steps.
