### ISSUE TITLE
Win 7 64 install error

### ISSUE THREAD

**Issue by mrzzcn** [Medium/phantomjs#343]
Error making request.
Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at TLSSocket.socketOnEnd (_http_client.js:293:23)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Please report this full log at https://github.com/Medium/phantomjs

**Comment by nicks** [comment]
this means your network isn't working. see:
https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout
