### ISSUE TITLE
Unable to NPM install on Windows

### ISSUE THREAD

**Issue by assanov** [Medium/phantomjs#351]
Hi.
While making `npm install` log force me post issue here
```bash
> phantomjs@1.9.17 install D:\MKTMCPM\client\node_modules\karma-phantomjs-launcher\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to C:\Users\SAssanov\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...

Error making request.
Error: certificate not trusted
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)

Please report this full log at https://github.com/Medium/phantomjs

```
**Environment:**
1. Windows 7 x64 Enterpirse, Service Pack 1
2. NPM version  2.10.1
3. full log - http://www.filedropper.com/npm-debug_1

**Notes**
Certificate fix was applied as described here http://blog.npmjs.org/post/78085451721/npms-self-signed-certificate-is-no-more

**Comment by assanov** [comment]
**Closed**
Fixe my issue with this - http://stackoverflow.com/questions/9626990/receiving-error-error-ssl-error-self-signed-cert-in-chain-while-using-npm#answer-9631045

Sorry for inconvenience
