### ISSUE TITLE
Phantom installation failed Error: EPERM, operation not permitted when installing phantomjs 1.91.17 on Windows

### ISSUE THREAD

**Issue by bleggett** [Medium/phantomjs#352]
Get the following error when installing phantomJS 1.9.17 on Windows 7 with nodejs 0.12.4 and npm 2.11.2

phantomJS 1.9.16 installs just fine.

```
Copying extracted folder C:\Users\xxxx\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1434493225586\phantomjs-1.9.8-windows -> D
:\xx\xx\xx\UI\node_modules\phantomjs\lib\phantom
Phantom installation failed { [Error: EPERM, operation not permitted 'D:\xx\xx\xx\UI\node_modules\phantomjs\lib\phantom\phantomjs.e
xe']
  errno: -4048,
  code: 'EPERM',
  path: 'D:\\xx\\xx\\xx\\UI\\node_modules\\phantomjs\\lib\\phantom\\phantomjs.exe',
  syscall: 'chmod' } Error: EPERM, operation not permitted 'D:\xx\xx\xx\UI\node_modules\phantomjs\lib\phantom\phantomjs.exe'
    at Error (native)
    at Object.fs.chmodSync (evalmachine.<anonymous>:948:18)
    at Object.chmodSync (D:\xx\xx\xx\UI\node_modules\phantomjs\node_modules\fs-extra\node_modules\graceful-fs\polyfills.js:141:17)
    at Promise._successFn (D:\xx\xx\xx\UI\node_modules\phantomjs\install.js:144:10)
    at Promise._call (D:\xx\xx\xx\UI\node_modules\phantomjs\node_modules\kew\kew.js:373:13)
    at Promise._withInput (D:\xx\xx\xx\UI\node_modules\phantomjs\node_modules\kew\kew.js:333:25)
    at Promise.resolve (D:\xx\xx\xx\UI\node_modules\phantomjs\node_modules\kew\kew.js:105:27)
    at resolver (D:\xx\xx\xx\UI\node_modules\phantomjs\node_modules\kew\kew.js:409:17)
    at next (D:\xx\xx\xx\UI\node_modules\phantomjs\node_modules\fs-extra\node_modules\rimraf\rimraf.js:72:7)
    at FSReqWrap.CB [as oncomplete] (D:\xx\xx\xx\UI\node_modules\phantomjs\node_modules\fs-extra\node_modules\rimraf\rimraf.js:108:
9)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "phantomjs@1.9.17"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.17 install: `node install.js`
npm ERR! Exit status
```

**Comment by bleggett** [comment]
Closing. Seems to be related to corporate A/V.
