### ISSUE TITLE
Support NPM 3.1+

### ISSUE THREAD

**Issue by robertbaker** [Medium/phantomjs#363]
Need to specify fsevents.

```
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configur
e.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d"
gyp ERR! cwd C:\git\pos\node_modules\fsevents
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN install:fsevents Couldn't install optional dependency: fsevents@0.3.6 install: `node-gyp rebuild`
npm WARN install:fsevents Exit status 1

> phantomjs@1.9.17 install C:\git\pos\node_modules\phantomjs
```

**Comment by nicks** [comment]
From the npm 3 release notes:
```
THIS IS BETA SOFTWARE. Yes, we're still reminding you of this. No, you can't be excused. npm@3 will remain in beta until we're confident that it's stable and have assessed the effect of the breaking changes on the community. 
```
https://github.com/npm/npm/blob/master/CHANGELOG.md

It is still very buggy. This is expected.
