### ISSUE TITLE
How to make phantomjs_cdnurl work with self-signed cert?

### ISSUE THREAD

**Issue by DukeyToo** [Medium/phantomjs#366]
In our build environment, I have `phantomjs_cdnurl` set to an https location on our internal network, due to proxy issues accessing external resources.  During install, I get this:

```
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
    at SecurePair.<anonymous> (tls.js:1367:32)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:979:10)
    at CleartextStream.read [as _read] (tls.js:471:13)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at EncryptedStream.write [as _write] (tls.js:368:25)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at EncryptedStream.Writable.write (_stream_writable.js:182:11)
    at write (_stream_readable.js:601:24)
```

...presumably because the internal mirror has a self-signed cert.  How do I get the download to accept the self-signed cert?

I already have `strict-ssl=false` for npm, but that does not help.

**Comment by nicks** [comment]
are you sure you're setting strict-ssl correctly? not sure why it would work for everyone else.

if all else fails, you can install phantomjs on PATH to side-step the process completely. see: https://github.com/Medium/phantomjs#i-tried-everything-but-my-network-is-b0rked-what-do-i-do

closing because this is a network problem at your end, and there is a clear workaround.
