### ISSUE TITLE
Error occur while running "npm install" for bootstrap-3.3.5

### ISSUE THREAD

**Issue by phgap** [Medium/phantomjs#374]
The error log as follow: 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Study\cui.jn\bootstrap\bootstrap-3.3.5\npm-debug.log

**Comment by RokaFogtaCsukaFarka** [comment]
Have the same problem!

So the error is the following:
`>phantom.js@1.19.18 install /localhost/myFolder/`
`>node install.js`
`
`module.js:338
`    throw err;`
`     ^`
`Error: Cannot find module '/var/www/html/pseudodoodle/node_modules/grunt-contrib-`
`qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js'`
 `   at Function.Module._resolveFilename (module.js:336:15)`
`    at Function.Module._load (module.js:278:25)`
`    at Function.Module.runMain (module.js:501:10)`
`    at startup (node.js:129:16)`
`    at node.js:814:3`

**Comment by jmls** [comment]
anyone find a solution to this ? Got the same problem

**Comment by kirillnovak** [comment]
I resolved this after ``/tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2`` been removed.

**Comment by jakekemple** [comment]
Do you have the correct version of node & npm installed? I used nvm to update my node to a newer version. If you are installing with 'npm install', that is

**Comment by amatecha** [comment]
Yeah, I had the same error and clearing /tmp/phantomjs fixed it for me.  Kinda nuts.  Node 0.10.37, npm 1.4.28

**Comment by ChrisLundquist** [comment]
Yes, clearing `/tmp/phantomjs` fixed it for me too using node 4.2.2 and npm 3.3.12

**Comment by romanrev** [comment]
Hey guys, do not want to sound didactic, but keeping the directory `/tmp/phantomjs` around and treating it as temporary thing is not right. Say another user is going to run the `npm install` - what happens? He'll be denied the rights to write into that directory. And so on.

**Comment by emanuelecasadio** [comment]
Got the same problem here and hasn't been able to fix it yet because I am running on a third-party PaaS.

**Comment by mmcelhinney** [comment]
I actually found that I had phantomjs installed globally so removed it , it seemed to have a problem unlinking the original

npm remove -g phantomjs 

then fire ahead with your install ....and I was working fine :) hope this helps ...sorry if has already been answered

**Comment by HorNeyMonKey** [comment]
npm install bootstrap@3
/home/himanshu
`-- bootstrap@3.3.7 

npm WARN enoent ENOENT: no such file or directory, open '/home/himanshu/package.json'
npm WARN himanshu No description
npm WARN himanshu No repository field.
npm WARN himanshu No README data
npm WARN himanshu No license field.


this is the problem i am facing while installing it using npm..help me..i am a new user of ubuntu
