### ISSUE TITLE
Certificate not trusted

### ISSUE THREAD

**Issue by shawngranner** [Medium/phantomjs#377]
I've pasted the contents of my command line window  & the npm-debug.log file after attempting to run a batch file that contains the following commands:

<BATCH FILE START>
@echo off
cd CompensationUI
call npm install --strict-ssl false
node node_modules/bower/bin/bower install
<BATCH FILE END>

<COMMAND LINE OUTPUT START>
npm WARN package.json CompensationUI@1.0.0 Normalized value of bugs field is an
empty object. Deleted.
npm WARN package.json CompensationUI@1.0.0 No README data
npm WARN peerDependencies The peer dependency phantomjs@>=1.9 included from karm
a-phantomjs-launcher will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.
/
> phantomjs2-ext@0.0.6 install C:\TFS2012_at\Financials\CHRW Financials\Financia
l Applications\CompensationUI\CompensationUI\node_modules\phantomjs2-ext
> node install.js

Downloading https://github.com/gskachkov/phantomjs/releases/download/2.0.0-20141
016-x86/phantomjs-2.0.0-20141016-win-x86.zip
Saving to C:\Users\gransha\AppData\Local\Temp\phantomjs\phantomjs-2.0.0-20141016
-win-x86.zip
Receiving...

Error making request.
Error: certificate not trusted
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)

Please report this full log at https://github.com/Medium/phantomjs
\
> phantomjs@1.9.18 install C:\TFS2012_at\Financials\CHRW Financials\Financial Ap
plications\CompensationUI\CompensationUI\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-wind
ows.zip
Saving to C:\Users\gransha\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.
zip
Receiving...

Error making request.
Error: certificate not trusted
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "--strict-ssl" "false"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs2-ext@0.0.6 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs2-ext@0.0.6 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs2-ext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs2-ext
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\TFS2012_at\Financials\CHRW Financials\Financial Applications\Com
pensationUI\CompensationUI\npm-debug.log
<COMMAND LINE OUTPUT END>

**Comment by liberalGeorge** [comment]
I also get this for 1.9.18
