### ISSUE TITLE
$ npm i -g phantomjs  window 2008

### ISSUE THREAD

**Issue by zanjs** [Medium/phantomjs#404]
```
$ npm i -g phantomjs
C:\Users\Administrator\AppData\Roaming\npm\phantomjs -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\phantomjs\bin\phantomjs

> phantomjs@1.9.18 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to C:\Users\ADMINI~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...

Error making request.
Error: read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TLSWrap.onread (net.js:544:26)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "phantomjs"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\zan\www\redux\react-redux-universal-hot-example\npm-debug.log

```

**Comment by nicks** [comment]
this means there's a problem with your internet, or something is blocking your connection to bitbucket. See
https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout
for more info and workarounds
