### ISSUE TITLE
Error on install phantomjs with npm

### ISSUE THREAD

**Issue by toni-moreno** [Medium/phantomjs#409]
This is the output log
````
[root@laboratorio grafana]# npm install phantomjs
npm WARN package.json grunt-contrib-htmlmin@0.1.3 No README data
npm WARN package.json karma-mocha@0.1.10 No README data
npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
npm WARN package.json rjs-build-analysis@0.0.3 No repository field.
npm WARN package.json expect.js@0.2.0 No repository field.
-
> phantomjs@1.9.18 install /root/gospace/src/github.com/grafana/grafana/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /root/gospace/src/github.com/grafana/grafana/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at TLSSocket.socketOnEnd (_http_client.js:293:23)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Linux 2.6.32-431.20.3.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "phantomjs"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/gospace/src/github.com/grafana/grafana/npm-debug.log
```

**Comment by toni-moreno** [comment]
Sorry It was a connectivity issue...
