### ISSUE TITLE
Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by IliyaTryapitsin** [Medium/phantomjs#419]
```
Error: Error: Command failed: node_modules/phantomjs/lib/phantom/bin/phantomjs: 4: node_modules/phantomjs/lib/phantom/bin/phantomjs: Syntax error: Unterminated quoted string
2015-12-04T08:29:09.541Z pid:20428 worker:2     at services/report-service.js:549:31
2015-12-04T08:29:09.541Z pid:20428 worker:2     at ChildProcess.exithandler (child_process.js:641:7)
2015-12-04T08:29:09.541Z pid:20428 worker:2     at ChildProcess.EventEmitter.emit (events.js:98:17)
2015-12-04T08:29:09.541Z pid:20428 worker:2     at maybeClose (child_process.js:743:16)
2015-12-04T08:29:09.542Z pid:20428 worker:2     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```
catch this exception on Ubuntu. 
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```
Well on MacOSX

**Comment by nicks** [comment]
this typically happens when you installed the binary on one platform and tried to run the installed code on another platform, which will not work. dupe #384

**Comment by IliyaTryapitsin** [comment]
I did installation, but problem continue.

**Comment by alexch** [comment]
@itryapitsin did you uninstall first? Try `npm uninstall phantomjs; npm install phantomjs`
