### ISSUE TITLE
phantomjs.js fails to locate & start the binary.

### ISSUE THREAD

**Issue by gjw** [Medium/phantomjs#435]
log leaves:
```
Internal/child_process.js:274
  var err = this._handle.spawn(options);
                         ^

Typeerror: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:362:9)
    at Object.<anonymous> (/Users/Gabriel/w/qa-stemeco/stem_eco_api/node_modules/phantomjs-server/node_modules/phantomjs/bin/phantomjs:32:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
```

tracing this back to 
```
/**
 * Where the phantom binary can be found.
 * @type {string}
 */
try {
  exports.path = path.resolve(__dirname, require('./location').location)
} catch(e) {
  // Must be running inside install script.
  exports.path = null
}
``` 
and actually re-raising the error results in a 
``` { [Error: Cannot find module './location'] code: 'MODULE_NOT_FOUND' } ```

Which does exist, as per a normal install, but for some reason is not being found.

**Comment by darrennolan** [comment]
I'm receiving this error exactly, on node 0.12.7.
If I switch to node 4.2.3 - I don't get this issue anymore.

**Comment by gjw** [comment]
Weird.  I've seen it on, and only tested it on node 5.1.0.
Seems to be something with the default load / module search path?  But I don't know (or atm care) enough to track it down further... just hardcoded the path to get around it for now.

**Comment by VWoeltjen** [comment]
Seeing this intermittently on node v0.12.2, npm 2.7.6

Upgraded to node v5.7.1, npm 3.6.0

Running an `rm -r node_modules ; npm cache clean` resolves the issue, at least sometimes. It does eventually recur, not sure what triggers this.

I do have a globally-installed phantomjs that does seem to be detected during the install process (I don't want it to be, but that is neither here nor there), wondering if that might trigger this issue

Doing some local debugging, I observe that `lib/location.js` (in the installed `node_modules/phantomjs-prebuilt`) is a small non-human-readable binary file; this seems to be the root cause of `null` value of the path at run-time. I see that this file is created during the install process, but am unsure of how to debug this to determine why this might be going wrong.

**Comment by sdbondi** [comment]
I'm using `yarn` and that seems to skip a build hook that downloads the binary - `npm install phantomjs-prebuilt` works.

**Comment by seansd** [comment]
I'm seeing the error also with phantomjs-prebuilt. . . We're going to try re-installing before running and see what happens

**Comment by johanflote** [comment]
this happened to me as well on 4.4.1. removing the global phantomjs and phantomjs-prebuilt and reinstalling fixed it

**Comment by vanloswang** [comment]
happened to me as well on 6.9.11 with phantomjs-prebuilt 2.1.5

**Comment by MarksCode** [comment]
so nobody has found a solution?

**Comment by tdeleanu** [comment]
Everything was working fine with node v11.
When I switched to v12 phantom prebuilt install is not ready for that so it has to recompile.
I had to upgrade some packages to handle node v12:
"grpc": "^1.20.2"
Also, I'm using "phantomjs-prebuilt": "^2.1.16".
