### ISSUE TITLE
Install script fails @2.1.1

### ISSUE THREAD

**Issue by emflores** [Medium/phantomjs#446]
As the title says, `npm install` fails @2.1.1. Appears to be an issue with the `fs-extra` version bump here: https://github.com/Medium/phantomjs/commit/2620fb283439181cab0a99b89fdf4532455bc35d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

```
> phantomjs@2.1.1 install /vagrant/node_modules/phantomjs
> node install.js

/vagrant/node_modules/fs-extra/node_modules/rimraf/node_modules/glob/node_modules/minimatch/minimatch.js:1
(function (exports, require, module, __filename, __dirname) { module.exports = minimatch
                                                                               ^

ReferenceError: minimatch is not defined
    at Object.<anonymous> (/vagrant/node_modules/fs-extra/node_modules/rimraf/node_modules/glob/node_modules/minimatch/minimatch.js:1:80)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/vagrant/node_modules/fs-extra/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
``` 

Environment

* Node 4.2.4
* Ubuntu 14.04 (via Vagrant/VirtualBox and Docker)

Repro 

* `rm -rf node_modules`
* `npm install`

**Comment by emflores** [comment]
Still not certain what the issue was, but an `rm -rf` of `/tmp/phantomjs` did the trick. I will let you decide if this one should be closed or not.

**Comment by nicks** [comment]
this sounds like you had a corrupt npm cache. it seems pretty unlikely that minimatch broke.
