### ISSUE TITLE
An error occur with npm install with phantomjs

### ISSUE THREAD

**Issue by origds** [Medium/phantomjs#463]
When I run `npm install` it throw this error 

```
phantomjs@1.9.19 install /Users/AkdemiaMacBookAir/Developer/GooruProjects/teams/node_modules/phantomjs
> node install.js
​
PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /Users/AkdemiaMacBookAir/Developer/GooruProjects/teams/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-macosx.zip
Using proxy http://proxy-server-address:8080/
Receiving...
​
Error making request.
Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy-server-address proxy-server-address:8080
    at ClientRequest.onError (/Users/AkdemiaMacBookAir/Developer/GooruProjects/teams/node_modules/phantomjs/node_modules/request/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:265:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at connectErrorNT (net.js:996:8)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
​
Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v2.13.1
npm ERR! code ELIFECYCLE
​
npm ERR! phantomjs@1.9.19 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.19 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
​
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/AkdemiaMacBookAir/Developer/GooruProjects/teams/npm-debug.log
```

I don't know how to fix it, please anyone can help me.

Thanks in advance.

**Comment by nicks** [comment]
you have a proxy set to `http://proxy-server-address:8080/`, which isn't resolving to anything.
