### ISSUE TITLE
Failed at the phantomjs-prebuilt@2.1.4 install script 'node install.js'

### ISSUE THREAD

**Issue by yura415** [Medium/phantomjs#480]
```
root@appsynd:~# npm i -g phantomjs-prebuilt
/root/.nvm/versions/node/v4.3.1/bin/phantomjs -> /root/.nvm/versions/node/v4.3.1/lib/node_modules/phantomjs-prebuilt/bin/phantomjs

> phantomjs-prebuilt@2.1.4 install /root/.nvm/versions/node/v4.3.1/lib/node_modules/phantomjs-prebuilt
> node install.js

module.js:340
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v4.3.1/lib/node_modules/phantomjs-prebuilt/install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
npm ERR! Linux 3.13.0-68-generic
npm ERR! argv "/root/.nvm/versions/node/v4.3.1/bin/node" "/root/.nvm/versions/node/v4.3.1/bin/npm" "i" "-g" "phantomjs-prebuilt"
npm ERR! node v4.3.1
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.4 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.4 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

[npm-debug.log](https://gist.github.com/yura415/742476da61d987f32a0e)

OS: Ubuntu 14.04.3 LTS
node v4.3.1 & npm v3.7.5
Also I'm using NVM

**Comment by gerbil** [comment]
Same here on windows 7

**Comment by nicks** [comment]
dupe #302

**Comment by elhay-av** [comment]
`$ sudo npm install` solve this issue for me.

**Comment by jasonwr** [comment]
@elhay-av  what if you're on a system where you're not allowed to use sudo (e.g. dev server). I'm getting the same error (RHEL 7 x86_64).

**Comment by jamescrosswell** [comment]
I ran into this today. Fixed by doing:

```
npm uninstall phantomjs2 --save-dev
npm install phantomjs-prebuilt --save-dev
```

phantomjs-prebuilt doesn't seem to have this issue. I guess phantomjs2 isn't very stable right now.

**Comment by giorgiosironi** [comment]
Notice how the title of this issue is `Failed at the *phantomjs-prebuilt@2.1.4* install script`.

**Comment by ganeshrajuLinaro** [comment]
I am getting the same error in ubuntu running on AARCH64 architecture

**Comment by nicks** [comment]
@ganeshrajuLinaro the relevant error is "Unexpected platform or architecture: linux/arm64". There are no binaries available for ARM, see the FAQ: https://github.com/Medium/phantomjs#im-using-an-unsupported-version-of-linux-or-an-arm-processor-i-get-errors-about-unexpected-platform-or-architecture-what-do-i-do

I'm going to lock this issue, because it's becoming a dumping ground for people confused by unrelated issues.
