### ISSUE TITLE
`npm install phantomjs-prebuilt` fails

### ISSUE THREAD

**Issue by melinath** [Medium/phantomjs#519]
I can't get phantomjs-prebuilt to install on my mac. I do already have a version of phantomjs installed via homebrew, in case that's relevant.

```
node v5.9.1
npm  v3.7.3
```

Here is the verbose debug log: [npm-debug.txt](https://github.com/Medium/phantomjs/files/194515/npm-debug.txt)

Here's the (slightly different) console log:

```
> phantomjs-prebuilt@2.1.7 install /Users/<username>/src/js/<project>/node_modules/phantomjs-prebuilt
> node install.js

module.js:341
    throw err;
    ^

Error: Cannot find module './util/assign'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/<username>/src/js/<project>/node_modules/fs-extra/lib/index.js:1:76)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
npm WARN banner-builder@1.0.0 license should be a valid SPDX license expression
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.9.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.7 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/<username>/src/js/<project>/npm-debug.log
```

**Comment by melinath** [comment]
Okay, so, I fixed the issue I was having by doing the following:

1. Removing phantom and phantomjs-prebuilt from my package.json.
2. Removing the node_modules directory.
3. running npm install
4. running npm install phantom

**Comment by nicks** [comment]
it looks like the error was deep in fs-extra, which is probably indicative of a broken npm cache. npm has caching bugs _shrug_. closing this as not actionable.
