### ISSUE TITLE
Error: tunneling socket could not be established, cause=Parse Error

### ISSUE THREAD

**Issue by Nipun317** [Medium/phantomjs#525]

**Comment by Nipun317** [comment]
Error making request.
[12:23:45][npm install] Error: tunneling socket could not be established, cause=Parse Error
[12:23:45][npm install]     at ClientRequest.onError (/home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/phantomjs/node_modules/request/node_modules/tunnel-agent/index.js:176:17)
[12:23:45][npm install]     at ClientRequest.g (events.js:180:16)
[12:23:45][npm install]     at ClientRequest.EventEmitter.emit (events.js:95:17)
[12:23:45][npm install]     at Socket.socketOnData (http.js:1588:9)
[12:23:45][npm install]     at TCP.onread (net.js:527:27)
[12:23:45][npm install] 
[12:23:45][npm install] Please report this full log at https://github.com/Medium/phantomjs
[12:23:45][npm install] npm http GET http://registry.npmjs.org/inherits
[12:23:45][npm install] npm ERR! weird error 1
[12:23:45][npm install] npm http 200 http://registry.npmjs.org/inherits
[12:23:45][npm install] npm ERR! Error: ENOENT, open '/home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423371364-0.635702497093007/package/internal/createReduce.js'
[12:23:45][npm install] npm ERR! If you need help, you may report this log at:
[12:23:45][npm install] npm ERR!     <http://github.com/isaacs/npm/issues>;
[12:23:45][npm install] npm ERR! or email it to:
[12:23:45][npm install] npm ERR!     <npm-@googlegroups.com>
[12:23:45][npm install] 
[12:23:45][npm install] npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
[12:23:45][npm install] npm ERR! command "node" "/usr/bin/npm" "install"
[12:23:45][npm install] npm ERR! cwd /home/syscompitdev/TeamCity/buildAgent/work/front-2470
[12:23:45][npm install] npm ERR! node -v v0.10.26
[12:23:45][npm install] npm ERR! npm -v 1.3.6
[12:23:45][npm install] npm ERR! path /home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423371364-0.635702497093007/package/internal/createReduce.js
[12:23:45][npm install] npm ERR! code ENOENT
[12:23:45][npm install] npm ERR! errno 34
[12:23:45][npm install] npm ERR! Error: ENOENT, utime '/home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423418550-0.30146631109528244/package/docs/class_goog_testing_FunctionCall.html'
[12:23:45][npm install] npm ERR! If you need help, you may report this log at:
[12:23:45][npm install] npm ERR!     <http://github.com/isaacs/npm/issues>;
[12:23:45][npm install] npm ERR! or email it to:
[12:23:45][npm install] npm ERR!     <npm-@googlegroups.com>
[12:23:45][npm install] 
[12:23:45][npm install] npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
[12:23:45][npm install] npm ERR! command "node" "/usr/bin/npm" "install"
[12:23:45][npm install] npm ERR! cwd /home/syscompitdev/TeamCity/buildAgent/work/front-2470
[12:23:45][npm install] npm ERR! node -v v0.10.26
[12:23:45][npm install] npm ERR! npm -v 1.3.6
[12:23:45][npm install] npm ERR! path /home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423418550-0.30146631109528244/package/docs/class_goog_testing_FunctionCall.html
[12:23:45][npm install] npm ERR! fstream_path /home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423418550-0.30146631109528244/package/docs/class_goog_testing_FunctionCall.html
[12:23:45][npm install] npm ERR! fstream_type File
[12:23:45][npm install] npm ERR! fstream_class FileWriter
[12:23:45][npm install] npm ERR! fstream_finish_call utimes
[12:23:45][npm install] npm ERR! code ENOENT
[12:23:45][npm install] npm ERR! errno 34
[12:23:45][npm install] npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:305:19
[12:23:45][npm install] npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
[12:23:45][npm install] npm ERR! tar pack Error reading /home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423424494-0.9800056903623044/package
[12:23:45][npm install] npm ERR! addLocalDirectory Could not pack "/home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423424494-0.9800056903623044/package" to "/home/syscompitdev/.npm/minimist/0.0.8/package.tgz"
[12:23:46][npm install] npm ERR! Error: ENOENT, lstat '/home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/handlebars/dist/handlebars.min.js'
[12:23:46][npm install] npm ERR! If you need help, you may report this log at:
[12:23:46][npm install] npm ERR!     <http://github.com/isaacs/npm/issues>;
[12:23:46][npm install] npm ERR! or email it to:
[12:23:46][npm install] npm ERR!     <npm-@googlegroups.com>
[12:23:46][npm install] 
[12:23:46][npm install] npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
[12:23:46][npm install] npm ERR! command "node" "/usr/bin/npm" "install"
[12:23:46][npm install] npm ERR! cwd /home/syscompitdev/TeamCity/buildAgent/work/front-2470
[12:23:46][npm install] npm ERR! node -v v0.10.26
[12:23:46][npm install] npm ERR! npm -v 1.3.6
[12:23:46][npm install] npm ERR! path /home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/handlebars/dist/handlebars.min.js
[12:23:46][npm install] npm ERR! fstream_path /home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/handlebars/dist/handlebars.min.js
[12:23:46][npm install] npm ERR! fstream_type File
[12:23:46][npm install] npm ERR! fstream_class FileWriter
[12:23:46][npm install] npm ERR! code ENOENT
[12:23:46][npm install] npm ERR! errno 34
[12:23:46][npm install] npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
[12:23:46][npm install] npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
[12:23:46][npm install] npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/fileset/node_modules/glob/node_modules/inherits'
[12:23:46][npm install] npm ERR! error rolling back  istanbul@0.2.16 { [Error: ENOTEMPTY, rmdir '/home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/fileset/node_modules/glob/node_modules/inherits']
[12:23:46][npm install] npm ERR! error rolling back   errno: 53,
[12:23:46][npm install] npm ERR! error rolling back   code: 'ENOTEMPTY',
[12:23:46][npm install] npm ERR! error rolling back   path: '/home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/fileset/node_modules/glob/node_modules/inherits' }
[12:23:46][npm install] npm ERR! Error: ENOENT, lstat '/home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/js-yaml/lib/js-yaml/type/float.js'
[12:23:46][npm install] npm ERR! If you need help, you may report this log at:
[12:23:46][npm install] npm ERR!     <http://github.com/isaacs/npm/issues>;
[12:23:46][npm install] npm ERR! or email it to:
[12:23:46][npm install] npm ERR!     <npm-@googlegroups.com>
[12:23:46][npm install] 
[12:23:46][npm install] npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
[12:23:46][npm install] npm ERR! command "node" "/usr/bin/npm" "install"
[12:23:46][npm install] npm ERR! cwd /home/syscompitdev/TeamCity/buildAgent/work/front-2470
[12:23:46][npm install] npm ERR! node -v v0.10.26
[12:23:46][npm install] npm ERR! npm -v 1.3.6
[12:23:46][npm install] npm ERR! path /home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/js-yaml/lib/js-yaml/type/float.js
[12:23:46][npm install] npm ERR! fstream_path /home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/js-yaml/lib/js-yaml/type/float.js
[12:23:46][npm install] npm ERR! fstream_type File
[12:23:46][npm install] npm ERR! fstream_class FileWriter
[12:23:46][npm install] npm ERR! code ENOENT
[12:23:46][npm install] npm ERR! errno 34
[12:23:46][npm install] npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
[12:23:46][npm install] npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
[12:23:46][npm install] npm ERR! Error: ENOENT, lstat '/home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/escodegen/node_modules/source-map/lib/source-map/array-set.js'
[12:23:46][npm install] npm ERR! If you need help, you may report this log at:
[12:23:46][npm install] npm ERR!     <http://github.com/isaacs/npm/issues>;
[12:23:46][npm install] npm ERR! or email it to:
[12:23:46][npm install] npm ERR!     <npm-@googlegroups.com>
[12:23:46][npm install] 
[12:23:46][npm install] npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
[12:23:46][npm install] npm ERR! command "node" "/usr/bin/npm" "install"
[12:23:46][npm install] npm ERR! cwd /home/syscompitdev/TeamCity/buildAgent/work/front-2470
[12:23:46][npm install] npm ERR! node -v v0.10.26
[12:23:46][npm install] npm ERR! npm -v 1.3.6
[12:23:46][npm install] npm ERR! path /home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/escodegen/node_modules/source-map/lib/source-map/array-set.js
[12:23:46][npm install] npm ERR! fstream_path /home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/escodegen/node_modules/source-map/lib/source-map/array-set.js
[12:23:46][npm install] npm ERR! fstream_type File
[12:23:46][npm install] npm ERR! fstream_class FileWriter
[12:23:46][npm install] npm ERR! code ENOENT
[12:23:46][npm install] npm ERR! errno 34
[12:23:46][npm install] npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
[12:23:46][npm install] npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
[12:23:46][npm install] npm http GET http://registry.npmjs.org/esmangle
[12:23:46][npm install] npm http GET http://registry.npmjs.org/source-map/0.1.11
[12:23:46][npm install] npm http GET http://registry.npmjs.org/StringScanner
[12:23:46][npm install] npm WARN optional dep failed, continuing cscodegen@git://github.com/michaelficarra/cscodegen.git#73fd7202ac086c26f18c9d56f025b18b3c6f5383
[12:23:46][npm install] npm http 200 http://registry.npmjs.org/source-map/0.1.11
[12:23:46][npm install] npm http 200 http://registry.npmjs.org/StringScanner
[12:23:46][npm install] npm http GET http://registry.npmjs.org/source-map/-/source-map-0.1.11.tgz
[12:23:46][npm install] npm ERR! Error: ENOENT, lstat '/home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/escodegen/node_modules/esprima/esprima.js'
[12:23:46][npm install] npm ERR! If you need help, you may report this log at:
[12:23:46][npm install] npm ERR!     <http://github.com/isaacs/npm/issues>;
[12:23:46][npm install] npm ERR! or email it to:
[12:23:46][npm install] npm ERR!     <npm-@googlegroups.com>
[12:23:46][npm install] 
[12:23:46][npm install] npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
[12:23:46][npm install] npm ERR! command "node" "/usr/bin/npm" "install"
[12:23:46][npm install] npm ERR! cwd /home/syscompitdev/TeamCity/buildAgent/work/front-2470
[12:23:46][npm install] npm ERR! node -v v0.10.26
[12:23:46][npm install] npm ERR! npm -v 1.3.6
[12:23:46][npm install] npm ERR! path /home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/escodegen/node_modules/esprima/esprima.js
[12:23:46][npm install] npm ERR! fstream_path /home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/escodegen/node_modules/esprima/esprima.js
[12:23:46][npm install] npm ERR! fstream_type File
[12:23:46][npm install] npm ERR! fstream_class FileWriter
[12:23:46][npm install] npm ERR! code ENOENT
[12:23:46][npm install] npm ERR! errno 34
[12:23:46][npm install] npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
[12:23:46][npm install] npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
[12:23:46][npm install] npm http 200 http://registry.npmjs.org/source-map/-/source-map-0.1.11.tgz
[12:23:46][npm install] npm ERR! Error: ENOENT, lstat '/home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423372219-0.7581567673478276/package/dist/less-1.7.1.min.js'
[12:23:46][npm install] npm ERR! If you need help, you may report this log at:
[12:23:46][npm install] npm ERR!     <http://github.com/isaacs/npm/issues>;
[12:23:46][npm install] npm ERR! or email it to:
[12:23:46][npm install] npm ERR!     <npm-@googlegroups.com>
[12:23:46][npm install] 
[12:23:46][npm install] npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
[12:23:46][npm install] npm ERR! command "node" "/usr/bin/npm" "install"
[12:23:46][npm install] npm ERR! cwd /home/syscompitdev/TeamCity/buildAgent/work/front-2470
[12:23:46][npm install] npm ERR! node -v v0.10.26
[12:23:46][npm install] npm ERR! npm -v 1.3.6
[12:23:46][npm install] npm ERR! path /home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423372219-0.7581567673478276/package/dist/less-1.7.1.min.js
[12:23:46][npm install] npm ERR! fstream_path /home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423372219-0.7581567673478276/package/dist/less-1.7.1.min.js
[12:23:46][npm install] npm ERR! fstream_type File
[12:23:46][npm install] npm ERR! fstream_class FileWriter
[12:23:46][npm install] npm ERR! code ENOENT
[12:23:46][npm install] npm ERR! errno 34
[12:23:46][npm install] npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
[12:23:46][npm install] npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
[12:23:46][npm install] npm ERR! Error: ENOENT, lstat '/home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423408068-0.44426452182233334/package/test/compare/traceur.js'
[12:23:46][npm install] npm ERR! If you need help, you may report this log at:
[12:23:46][npm install] npm ERR!     <http://github.com/isaacs/npm/issues>;
[12:23:46][npm install] npm ERR! or email it to:
[12:23:46][npm install] npm ERR!     <npm-@googlegroups.com>
[12:23:46][npm install] 
[12:23:46][npm install] npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
[12:23:46][npm install] npm ERR! command "node" "/usr/bin/npm" "install"
[12:23:46][npm install] npm ERR! cwd /home/syscompitdev/TeamCity/buildAgent/work/front-2470
[12:23:46][npm install] npm ERR! node -v v0.10.26
[12:23:46][npm install] npm ERR! npm -v 1.3.6
[12:23:46][npm install] npm ERR! path /home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423408068-0.44426452182233334/package/test/compare/traceur.js
[12:23:46][npm install] npm ERR! fstream_path /home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423408068-0.44426452182233334/package/test/compare/traceur.js
[12:23:46][npm install] npm ERR! fstream_type File
[12:23:46][npm install] npm ERR! fstream_class FileWriter
[12:23:46][npm install] npm ERR! code ENOENT
[12:23:46][npm install] npm ERR! errno 34
[12:23:46][npm install] npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
[12:23:46][npm install] npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
[12:23:46][npm install] npm ERR! Error: ENOENT, lstat '/home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/lodash/dist/lodash.underscore.js'
[12:23:46][npm install] npm ERR! If you need help, you may report this log at:
[12:23:46][npm install] npm ERR!     <http://github.com/isaacs/npm/issues>;
[12:23:46][npm install] npm ERR! or email it to:
[12:23:46][npm install] npm ERR!     <npm-@googlegroups.com>
[12:23:46][npm install] 
[12:23:46][npm install] npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
[12:23:46][npm install] npm ERR! command "node" "/usr/bin/npm" "install"
[12:23:46][npm install] npm ERR! cwd /home/syscompitdev/TeamCity/buildAgent/work/front-2470
[12:23:46][npm install] npm ERR! node -v v0.10.26
[12:23:46][npm install] npm ERR! npm -v 1.3.6
[12:23:46][npm install] npm ERR! path /home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/lodash/dist/lodash.underscore.js
[12:23:46][npm install] npm ERR! fstream_path /home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/lodash/dist/lodash.underscore.js
[12:23:46][npm install] npm ERR! fstream_type File
[12:23:46][npm install] npm ERR! fstream_class FileWriter
[12:23:46][npm install] npm ERR! code ENOENT
[12:23:46][npm install] npm ERR! errno 34
[12:23:46][npm install] npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
[12:23:46][npm install] npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
[12:23:46][npm install] npm http 200 http://registry.npmjs.org/esmangle
[12:23:46][npm install] npm ERR! tar pack Error reading /home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423395777-0.3993836776353419/package
[12:23:46][npm install] npm ERR! addLocalDirectory Could not pack "/home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423395777-0.3993836776353419/package" to "/home/syscompitdev/.npm/handlebars/4.0.5/package.tgz"
[12:23:46][npm install] npm ERR! Error: ENOENT, lstat '/home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/escodegen/node_modules/esprima/test/test.js'
[12:23:46][npm install] npm ERR! If you need help, you may report this log at:
[12:23:46][npm install] npm ERR!     <http://github.com/isaacs/npm/issues>;
[12:23:46][npm install] npm ERR! or email it to:
[12:23:46][npm install] npm ERR!     <npm-@googlegroups.com>
[12:23:46][npm install] 
[12:23:46][npm install] npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
[12:23:46][npm install] npm ERR! command "node" "/usr/bin/npm" "install"
[12:23:46][npm install] npm ERR! cwd /home/syscompitdev/TeamCity/buildAgent/work/front-2470
[12:23:46][npm install] npm ERR! node -v v0.10.26
[12:23:46][npm install] npm ERR! npm -v 1.3.6
[12:23:46][npm install] npm ERR! path /home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/escodegen/node_modules/esprima/test/test.js
[12:23:46][npm install] npm ERR! fstream_path /home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/escodegen/node_modules/esprima/test/test.js
[12:23:46][npm install] npm ERR! fstream_type File
[12:23:46][npm install] npm ERR! fstream_class FileWriter
[12:23:46][npm install] npm ERR! code ENOENT
[12:23:46][npm install] npm ERR! errno 34
[12:23:46][npm install] npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
[12:23:46][npm install] npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
[12:23:46][npm install] npm ERR! tar pack Error reading /home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423371204-0.39383598999120295/package
[12:23:46][npm install] npm ERR! addLocalDirectory Could not pack "/home/syscompitdev/TeamCity/buildAgent/temp/buildTmp/npm-10714-UFXBCEKW/1459423371204-0.39383598999120295/package" to "/home/syscompitdev/.npm/jshint/2.9.1/package.tgz"
[12:23:46][npm install] npm ERR! Error: ENOENT, lstat '/home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/esprima/test/test.js'
[12:23:46][npm install] npm ERR! If you need help, you may report this log at:
[12:23:46][npm install] npm ERR!     <http://github.com/isaacs/npm/issues>;
[12:23:46][npm install] npm ERR! or email it to:
[12:23:46][npm install] npm ERR!     <npm-@googlegroups.com>
[12:23:46][npm install] 
[12:23:46][npm install] npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
[12:23:46][npm install] npm ERR! command "node" "/usr/bin/npm" "install"
[12:23:46][npm install] npm ERR! cwd /home/syscompitdev/TeamCity/buildAgent/work/front-2470
[12:23:46][npm install] npm ERR! node -v v0.10.26
[12:23:46][npm install] npm ERR! npm -v 1.3.6
[12:23:46][npm install] npm ERR! path /home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/esprima/test/test.js
[12:23:46][npm install] npm ERR! fstream_path /home/syscompitdev/TeamCity/buildAgent/work/front-2470/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/esprima/test/test.js
[12:23:46][npm install] npm ERR! fstream_type File
[12:23:46][npm install] npm ERR! fstream_class FileWriter
[12:23:46][npm install] npm ERR! code ENOENT
[12:23:46][npm install] npm ERR! errno 34
[12:23:46][npm install] npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
[12:23:46][npm install] npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)

**Comment by nicks** [comment]
This is an NPM error and has nothing to do with this package.
