### ISSUE TITLE
phantomjs regularly fails to install via npm install

### ISSUE THREAD

**Issue by dodtsair** [Medium/phantomjs#527]
Often times (a couple times a week) we fail to install phatomjs via npm install.  The log is aways fairly basic:

```
00:01:22.526 npm ERR! 
00:01:22.526 npm ERR! Additional logging details can be found in:
00:01:22.526 npm ERR!     /scratch/jenkins/workspace/ic/release/d1-denim.vienna.release/njs-app/npm-debug.log
00:01:22.526 npm ERR! not ok code 0
00:01:22.560 [18:19:26] npm exited with non-zero code 1 , run `npm install` manually
00:01:22.560 
00:01:22.560 events.js:72
00:01:22.561         throw er; // Unhandled 'error' event
00:01:22.561               ^
00:01:22.562 Error: npm exited with non-zero code 1
00:01:22.562     at ChildProcess.<anonymous> (/scratch/jenkins/workspace/ic/release/d1-denim.vienna.release/node_modules/gulp-install/lib/commandRunner.js:14:19)
00:01:22.562     at ChildProcess.emit (events.js:98:17)
00:01:22.562     at maybeClose (child_process.js:756:16)
00:01:22.562     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
00:01:22.579 Build step 'Execute shell' marked build as failure
```

And in the npm log:
```
75166 error phantomjs@2.1.3 install: `node install.js`
75166 error Exit status 1
75167 error Failed at the phantomjs@2.1.3 install script.
75167 error This is most likely a problem with the phantomjs package,
75167 error not with npm itself.
75167 error Tell the author that this fails on your system:
75167 error     node install.js
75167 error You can get their info via:
75167 error     npm owner ls phantomjs
75167 error There is likely additional logging output above.
75168 error System Linux 3.13.0-71-generic
75169 error command "/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/0.10.30/bin/node" "/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/0.10.30/bin/npm" "install"
75170 error cwd /scratch/jenkins/workspace/ic/release/d1-denim.vienna.release/njs-app
75171 error node -v v0.10.30
75172 error npm -v 1.4.21
```

Relevant logs from the build:
```
00:00:31.775 npm WARN deprecated phantomjs@2.1.3: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
...
00:01:05.009 > phantomjs@2.1.3 install /scratch/jenkins/workspace/ic/release/d1-denim.vienna.release/njs-app/node_modules/phantomjs
00:01:05.009 > node install.js
00:01:05.009 
00:01:05.560 PhantomJS not found on PATH
00:01:05.561 Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
00:01:05.561 Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
00:01:05.562 Receiving...
00:01:05.615 
00:01:05.615 Error requesting archive.
00:01:05.615 Status: 403
00:01:05.615 Request options: {
00:01:05.615   "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2",
00:01:05.615   "encoding": null,
00:01:05.615   "followRedirect": true,
00:01:05.615   "headers": {
00:01:05.615     "User-Agent": "npm/1.4.21 node/v0.10.30 linux x64"
00:01:05.615   },
00:01:05.615   "strictSSL": true
00:01:05.615 }
00:01:05.615 Response headers: {
00:01:05.615   "x-amz-request-id": "E880BC8F4B3F87FC",
00:01:05.615   "x-amz-id-2": "3g420YmA70reTB7BZgcebyaPEihrOmei8G/bDCnrAKtnsRduuWZsAStAemUfJtPYdWvCDSP8moY=",
00:01:05.615   "content-type": "application/xml",
00:01:05.615   "transfer-encoding": "chunked",
00:01:05.615   "date": "Wed, 06 Apr 2016 22:19:08 GMT",
00:01:05.615   "server": "AmazonS3"
00:01:05.615 }
00:01:05.615 Make sure your network and proxy settings are correct.
00:01:05.615 
00:01:05.615 If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs
00:01:05.628 npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.30","npm":"1.4.21"})
00:01:06.055 npm ERR! phantomjs@2.1.3 install: `node install.js`
00:01:06.056 npm ERR! Exit status 1
00:01:06.056 npm ERR! 
00:01:06.056 npm ERR! Failed at the phantomjs@2.1.3 install script.
00:01:06.056 npm ERR! This is most likely a problem with the phantomjs package,
00:01:06.056 npm ERR! not with npm itself.
00:01:06.057 npm ERR! Tell the author that this fails on your system:
00:01:06.057 npm ERR!     node install.js
00:01:06.057 npm ERR! You can get their info via:
00:01:06.058 npm ERR!     npm owner ls phantomjs
00:01:06.058 npm ERR! There is likely additional logging output above.
00:01:06.058 
00:01:06.059 npm ERR! System Linux 3.13.0-71-generic
00:01:06.059 npm ERR! command "/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/0.10.30/bin/node" "/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/0.10.30/bin/npm" "install"
00:01:06.059 npm ERR! cwd /scratch/jenkins/workspace/ic/release/d1-denim.vienna.release/njs-app
00:01:06.060 npm ERR! node -v v0.10.30
00:01:06.060 npm ERR! npm -v 1.4.21
```

This one component is extremely unstable, for know I think the best approach for us is to remove our dependency on it.

**Comment by nicks** [comment]
did you notice the warning in the logs you posted?
> 00:00:31.775 npm WARN deprecated phantomjs@2.1.3: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'

`phantomjs` is deprecated and does not get updates. I think you'll find it will work better if you update to `phantomjs-prebuilt`
