### ISSUE TITLE
PhantomJS not found on PATH

### ISSUE THREAD

**Issue by pod4g** [Medium/phantomjs#541]
```
node v6.0.0
npm  v3.8.6
os   Darwin 15.4.0 darwin x64
```

I execute command ```sudo npm update``` (In fact, there are other commands can cause this error) and get the below error

```

> phantomjs@1.9.20 install /Users/liyanfeng/work/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-macosx.zip
Saving to /Users/liyanfeng/work/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...

Error making request.
Error: connect ETIMEDOUT 54.231.10.121:443
    at Object.exports._errnoException (util.js:896:11)
    at exports._exceptionWithHostPort (util.js:919:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1073:14)

Please report this full log at https://github.com/Medium/phantomjs
work@0.0.0 /Users/liyanfeng/work
└── (empty)

npm WARN work@0.0.0 No description
npm WARN work@0.0.0 No repository field.
npm WARN work@0.0.0 No license field.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Use

```

**Comment by LeeJim** [comment]
i had the same question,too

**Comment by nicks** [comment]
The error says that your connection timed out, likely because of a network problem on your end. See:
https://github.com/Medium/phantomjs#troubleshooting

**Comment by LeeJim** [comment]
I am just have a question. how to put it on the PATH on widonw10

**Comment by ajaytiwari52** [comment]
I had the same issue. I downloaded phantomjs manually and kept in temp folder of system ..temp/phantomjs/phantomjs-1.9.8-windows.zip.  It works.

**Comment by lin-credible** [comment]
@pod4g 哥们儿，完了你是咋搞定滴咧？

**Comment by kuangthien** [comment]
@ajaytiwari52  Thanks for your help, I did as your guide. But the install log still has this warning:

"npm WARN enoent ENOENT: no such file or directory, open 'c:\Users\ThienTQ1\Desktop\botay\node_modules\phantomjs\package.
json'"

How can I complete the installing for it?

thx in advance
