### ISSUE TITLE
Error during npm install

### ISSUE THREAD

**Issue by Bhaskar-nvipani** [Medium/phantomjs#548]
> This is an error occurred during the "npm install". I could not understand the root cause. It is reproducible. The platform details and nodejs, npm versions are at the end of the log below.

es/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1463861636506/phantomjs-1.9.8-linux-x86_64 -> /home/root/node_modules/jsreport/node_modules/toner-phantom/node_modules/phantom-html-to-pdf/node_modules/phantom-workers/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/root/node_modules/jsreport/node_modules/toner-phantom/node_modules/phantom-html-to-pdf/node_modules/phantom-workers/node_modules/phantomjs/lib/phantom/bin/phantomjs

Error making request.
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 1
npm ERR! not ok code 0
**root@ubuntu:/home/root# lsb_release -a**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
root@ubuntu:/home/root#
**root@ubuntu:/home/root# which node**
/usr/bin/node
**root@ubuntu:/home/root# ls -l /usr/bin/node**
lrwxrwxrwx 1 root root 6 Mar 27  2014 /usr/bin/node -> nodejs
root@ubuntu:/home/root#
**root@ubuntu:/home/root# node --version**
v0.10.25
**root@ubuntu:/home/root# npm --version**
1.3.10
root@ubuntu:/home/root#
root@ubuntu:/home/root# gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Bhaskar-nvipani** [comment]
Closing this issue as I found that the issue is with bitbucket. It was throwing 403 error most of the time when npm tries to download phantomjs. There is another issue with the version of npm I was using. It was resulting in a race condition. Closing this issue as it is not related to the code.
