### ISSUE TITLE
npm install phantomjs -g  or npm install  command

### ISSUE THREAD

**Issue by hudi02** [Medium/phantomjs#550]
Error making request.
Error: socket hang up
    at createHangUpError (_http_client.js:211:15)
    at TLSSocket.socketOnEnd (_http_client.js:303:23)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
 
Windows_NT 6.1.7601
 argv "D:\\Nodejs\\node.exe" "D:\\Nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "phantomjs" "-g"
 node v4.4.5
 npm  v2.15.5
 code ELIFECYCLE

 phantomjs@2.1.7 install: `node install.js`
 Exit status 1

**Comment by nicks** [comment]
`socket hang up` means that you're having a network problem at your end. see
https://github.com/Medium/phantomjs#troubleshooting
for more info
