### ISSUE TITLE
Install failure inside Docker running Node.js 6.2.1

### ISSUE THREAD

**Issue by westy92** [Medium/phantomjs#553]
Using the base Docker image node:6.2.1, phantomjs-prebuilt@2.1.7 fails to install.

From the logs:
```
[-----8<----cut-----8<------]
npm info lifecycle request-progress@2.0.1~install: request-progress@2.0.1
[-----8<----cut-----8<------]
npm info lifecycle phantomjs-prebuilt@2.1.7~install: phantomjs-prebuilt@2.1.7

> phantomjs-prebuilt@2.1.7 install /node_modules/phantomjs-prebuilt
> node install.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'request-progress'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/phantomjs-prebuilt/install.js:9:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
npm verb lifecycle phantomjs-prebuilt@2.1.7~install: unsafe-perm in lifecycle false
npm verb lifecycle phantomjs-prebuilt@2.1.7~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/node_modules/phantomjs-prebuilt/node_modules/.bin:/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle phantomjs-prebuilt@2.1.7~install: CWD: /node_modules/phantomjs-prebuilt
npm info lifecycle phantomjs-prebuilt@2.1.7~install: Failed to exec install script
npm verb unlock done using /root/.npm/_locks/staging-781faa38490e6896.lock for /node_modules/.staging
[-----8<----cut-----8<------]
npm verb stack Error: phantomjs-prebuilt@2.1.7 install: `node install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:852:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm verb pkgid phantomjs-prebuilt@2.1.7
npm verb cwd /
npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production" "--verbose"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.7 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
The command '/bin/sh -c npm install --production --verbose' returned a non-zero code: 1
```

**Comment by westy92** [comment]
I just got this to work on one machine and haven't changed a thing.  I can magically install it locally on ubuntu 15.10 but not on my CI server running 14.04.  It previously wasn't working on either.

**Comment by nicks** [comment]
the error message suggests that you didn't have `node` installed on PATH. i suspect you're running into this problem:
https://github.com/Medium/phantomjs#im-on-debian-or-ubuntu-and-the-installer-failed-because-it-couldnt-find-node

**Comment by westy92** [comment]
Sorry, but I'm not sure that's the issue.  I have `node` installed on PATH.  I ran `which node` and it found it right away.  Also, updating my PATH to explicitly contain the folder with the node binary did not help.  I also tried to install `nodejs-legacy` with no luck.
