### ISSUE TITLE
"..getaddrinfo ENOTFOUND.." during installation by phantomjs-prebuilt

### ISSUE THREAD

**Issue by justus-alex** [Medium/phantomjs#561]
The package being installed is html-pdf. Full log:

> ~: npm i html-pdf --save
\
&gt; phantomjs-prebuilt@2.1.7 install /home/j_alex/projects/b2b/node_modules/html-pdf/node_modules/phantomjs-prebuilt
&gt; node install.js

> PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

>Error making request.
Error: getaddrinfo ENOTFOUND github-cloud.s3.amazonaws.com github-cloud.s3.amazonaws.com:443
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)

>Please report this full log at https://github.com/Medium/phantomjs
npm WARN optional dep failed, continuing phantomjs-prebuilt@2.1.7
html-pdf@2.0.1 node_modules/html-pdf

**Comment by justus-alex** [comment]
Well, installed it well right now. Probably, some temporary network issue.
