### ISSUE TITLE
2.1.8 installation issues

### ISSUE THREAD

**Issue by NicolasPelletier** [Medium/phantomjs#584]
When I put `phantomjs-prebuilt` as a dependency of my project, I get the following on `npm install`:
```
> phantomjs-prebuilt@2.1.8 install /Users/pelletn/<MyProject>/node_modules/phantomjs-prebuilt
> node install.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'generate-object-property'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/pelletn/<MyProject>/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/index.js:1:76)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

I delete my node_modules, I try again, I get:
```
> phantomjs-prebuilt@2.1.8 install /Users/pelletn/<MyProject>/node_modules/phantomjs-prebuilt
> node install.js

module.js:327
    throw err;
    ^

Error: Cannot find module './writer'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/pelletn/<MyProject>/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/asn1/lib/ber/index.js:7:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

If I do `npm install || npm install` then I am fine, but I don't want to have to run `npm install` twice.

I am using: 
 - Node 4.4.7
 - npm 2.15.8
 - Mac OSX 10.11.6

**Comment by nicks** [comment]
should be fixed in v2.1.9

**Comment by NicolasPelletier** [comment]
It is indeed. Many thanks.

**Comment by ajbeach2** [comment]
This doesn't appear to be fixed or it has regressed, as I am getting the same issue in 2.1.14
