### ISSUE TITLE
1.9.0-4 fails to build as root

### ISSUE THREAD

**Issue by dcramer** [Medium/phantomjs#59]
I'm not sure what changed, but we were installing packages using sudo npm install (not for any particular reason), and now it hits a permission denied when attempting to copy the binary.

```
Phantom installation failed Error: EACCES, permission denied '/home/ubuntu/tmp/phantomjs'
    at Object.fs.mkdirSync (fs.js:483:18)
    at mkdir (/opt/run/ee7627cda855db2d14060e189bc7fa55ea8d8723/tenxer/node_modules/phantomjs/install.js:205:8)
    at Promise._successFn (/opt/run/ee7627cda855db2d14060e189bc7fa55ea8d8723/tenxer/node_modules/phantomjs/install.js:57:7)
    at Promise._withInput (/opt/run/ee7627cda855db2d14060e189bc7fa55ea8d8723/tenxer/node_modules/phantomjs/node_modules/kew/kew.js:204:25)
    at Promise._chainPromise (/opt/run/ee7627cda855db2d14060e189bc7fa55ea8d8723/tenxer/node_modules/phantomjs/node_modules/kew/kew.js:244:13)
    at Promise.then (/opt/run/ee7627cda855db2d14060e189bc7fa55ea8d8723/tenxer/node_modules/phantomjs/node_modules/kew/kew.js:144:13)
    at /opt/run/ee7627cda855db2d14060e189bc7fa55ea8d8723/tenxer/node_modules/phantomjs/install.js:55:23
    at loadCbs.length (/opt/run/ee7627cda855db2d14060e189bc7fa55ea8d8723/tenxer/node_modules/phantomjs/node_modules/npmconf/npmconf.js:76:7)
    at Array.forEach (native)
    at /opt/run/ee7627cda855db2d14060e189bc7fa55ea8d8723/tenxer/node_modules/phantomjs/node_modules/npmconf/npmconf.js:75:13
```

**Comment by mhawila** [comment]
We are getting the same problem with 1.9.8 even after using 'npm config set tmp /some/writable/path' configuration. The strange thing is, it seems phantom uses system tmp directory (i.e. /tmp)

**Comment by scf37** [comment]
Hit the same issue running npm install from Docker container as root.

```
+ whoami
root
+ mkdir -p /data/data/workspace/adminui-dev/node_modules/phantomjs/phantomjs
+ mkdir -p /data/data/workspace/adminui-dev/node_modules/phantomjs/tmp
+ mkdir /tmp/phantomjs
+ npm install
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> phantomjs@1.9.20 install /data/data/workspace/adminui-dev/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
/data/data/workspace/adminui-dev/node_modules/phantomjs/phantomjs is not writable: EACCES: permission denied, mkdir '/data/data/workspace/adminui-dev/node_modules/phantomjs/phantomjs'
/tmp/phantomjs is not writable: EACCES: permission denied, open '/tmp/phantomjs/1510845218509.tmp'
/data/data/workspace/adminui-dev/node_modules/phantomjs/tmp/phantomjs is not writable: EACCES: permission denied, mkdir '/data/data/workspace/adminui-dev/node_modules/phantomjs/tmp'
Can not find a writable tmp directory, please report issue on https://github.com/Obvious/phantomjs/issues/59 with as much information as possible.

``

As you can see, I'm running this as root and even creating directories does not help.

**Comment by scf37** [comment]
Digged from #707 : `npm install --unsafe-perm` helped.
