### ISSUE TITLE
ReferenceError: util is not defined - while installing from source

### ISSUE THREAD

**Issue by ganeshrajuLinaro** [Medium/phantomjs#611]
when i try to do 'node ./install.js', after downloading the source, i get the below error:

var checkPhantomjsVersion = util.checkPhantomjsVersion
                            ^

ReferenceError: util is not defined
    at Object.<anonymous> (/home/ganesh.raju/linaro/src/phantomjs/install.js:12:29)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

**Comment by Roam-Cooper** [comment]
Getting this too.

**Comment by cleathers** [comment]
I'm not sure what version y'all are running, but I was running into this issue as well.

After updating from `1.9.1-0` to `1.9.20` the issue resolved itself. Not sure if you all will have the same luck but it's worth giving it a try.
