### ISSUE TITLE
SSL error during npm install

### ISSUE THREAD

**Issue by dwightdegroff** [Medium/phantomjs#613]
> phantomjs2-ext@0.2.2 install /var/lib/jenkins/jobs/QA-Complete-Test/workspace/dwa/node_modules/karma-phantomjs2-launcher/node_modules/phantomjs2-ext
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /var/lib/jenkins/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: 140357198329920:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:769:

    at SlabBuffer.use (tls.js:235:18)
    at CleartextStream.read [as _read] (tls.js:455:29)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by dwightdegroff** [comment]
Looks like this is a firewall issue on my part. I'm loading phantomJS2 via karma-phantomjs2-launcher and for some reason they seem to be preferring your alternative mirror instead of the main.
