### ISSUE TITLE
install fails on codeship

### ISSUE THREAD

**Issue by tlenex** [Medium/phantomjs#620]
"version": "2.1.12"

```
> phantomjs-prebuilt@2.1.12 install /home/rof/src/bitbucket.org/spicypx/3sv.pl-frontend/node_modules/phantomjs-prebuilt
> node install.js

module.js:457
throw err;
^

Error: Cannot find module './utils'
at Function.Module._resolveFilename (module.js:455:15)
at Function.Module._load (module.js:403:25)
at Module.require (module.js:483:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/home/rof/src/bitbucket.org/myorg/repo1/node_modules/http-signature/lib/parser.js:5:13)
at Module._compile (module.js:556:32)
at Object.Module._extensions..js (module.js:565:10)
at Module.load (module.js:473:32)
at tryModuleLoad (module.js:432:12)
at Function.Module._load (module.js:424:3)
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN codelyzer@0.0.28 requires a peer of tslint@^3.9.0 but none was installed.
npm WARN repo1@1.0.0 No repository field.
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/home/rof/.nvm/versions/node/v6.5.0/bin/node" "/home/rof/.nvm/versions/node/v6.5.0/bin/npm" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.12 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.12 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.
```

**Comment by mbaaro** [comment]
Do this.....open the node cmd as admin...... stop your antivirus......
install npm globally .....reopen the CLI and enjoy!!!!!

**Comment by tlenex** [comment]
Antivirus on codeship, woot? On my PC code is runnig fine.
Codeship.com uses nvm for installing node, but I don't think using sudo in their cli is a good idea.
