### ISSUE TITLE
Error: connect ETIMEDOUT 192.30.253.11:443

### ISSUE THREAD

**Issue by aeharding** [Medium/phantomjs#634]
This may have to do with the DynDNS outage, but I just thought that I'd document this error I was having if anyone else has the same issue.

```
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /builds/my_project/my_project/node_modules/phantomjs-prebuilt: Command failed.
Exit code: 1
Command: sh
Arguments: -c node install.js
Directory: /builds/my_project/my_project/node_modules/phantomjs-prebuilt
Output:
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: connect ETIMEDOUT 192.30.253.11:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
```

node 6, npm 3, installing via yarn (but same thing happens with npm).

If this is a DynDNS issue, I'll close this as soon as it starts working again.
Thanks!

**Comment by aeharding** [comment]
I determined the root cause. Was related to DynDNS outage due to reactions by different party(s) (GitHub, Gitlab).

https://gitlab.com/gitlab-com/support-forum/issues/1219
