### ISSUE TITLE
2.1.13 binary fails with TypeError: Bad argument

### ISSUE THREAD

**Issue by liatreis** [Medium/phantomjs#640]
Upon running the binary:

```
internal/child_process.js:289
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at exports.spawn (child_process.js:385:9)
    at Object.<anonymous> (node_modules/phantomjs-prebuilt/bin/phantomjs:22:10)
```

Re-installing via `npm` or `yarn` didn't work. Resorted to reverting back to 2.1.4 and that worked ok.

This is on OS X with Node 7.1.0

**Comment by MCTaylor17** [comment]
I'm also experiencing this.  Restarting the app fixes it temporarily, but it consistently returns over time.

```
TypeError: Bad argument
	at TypeError (native)
	at ChildProcess.spawn (internal/child_process.js:289:26)
	at exports.spawn (child_process.js:380:9)
	at Object.exports.execFile (child_process.js:143:15)
```

**Comment by rosskevin** [comment]
Reproducible with:

```
./node_modules/.bin/phantomjs --version 
```

**Comment by adamreisnz** [comment]
Restarting app and reinstalling all node modules did not solve this issue for us. Any clue as to what might be causing it? This is with a pre-built version of phantomjs, have tested on both Node 7.4.0 and 7.6.0, running on OS X.

**Comment by MCTaylor17** [comment]
@adamreisnz Does it work momentarily?  

For me, it would work for a short time after restart.  A few days later it would stop working again.

**Comment by adamreisnz** [comment]
With 2.1.4 it works right away. With 2.1.14 it fails right away.

**Comment by adamreisnz** [comment]
Looks like this is fixed with 2.1.15 on Node 8. Not sure when it got fixed along the way, but can probably close this issue.

**Comment by adamreisnz** [comment]
Scratch that, still failing with the same error on Heroku when trying to install the package.
