### ISSUE TITLE
Failed at the phantomjs-prebuilt@2.1.13 install script 'node install.js'. on windows 7

### ISSUE THREAD

**Issue by rohithkrajan** [Medium/phantomjs#649]
I am trying to install phantomjs on a windows 7 machine and am getting this error .

```
npm ERR! Windows_NT 6.1.7601  
npm ERR! argv "C:\\Program Files (x86)\\nodist\\v\\nodev5.5.0\\node.exe"   "C:\\Program Files (x86)\\nodist\\bin\\node_mod  
ules\\npm\\bin\\npm-cli.js" "install"  
npm ERR! node v5.5.0  
npm ERR! npm  v3.10.9  
npm ERR! code ELIFECYCLE  

npm ERR! phantomjs-prebuilt@2.1.13 install: `node install.js`  
npm ERR! Exit status 1  
npm ERR!  
npm ERR! Failed at the phantomjs-prebuilt@2.1.13 install script 'node   install.js'.  
npm ERR! Make sure you have the latest version of node.js and npm installed.
```

There are many issues logged  in the phantomjs github repo for the same  or [this](http://stackoverflow.com/questions/26645207/npm-install-error-failed-at-the-phantomjs1-9-12-install-script) SO questionbut none of it is helping in my case.

This is what is the state of my machine

 - I have phantomjs installed locally at **C:\npm\phantomjs-2.1.1-windows\bin\phantomjs.exe** but when I run the npm install,it will always try to install by downloading which is where the problem for me.My corporate proxy is blocking the direct downloads .I also cannot use the  `--phantomjs_cdnurl` switch mentioned here https://www.npmjs.com/package/phantomjs#deciding-where-to-get-phantomjs
 - I can run the command and it works fine
        `phantomjs -v  
         2.1.1 ` 

But when I run `npm install ` on my project it is trying to install the phantomjs and will run into the above error.Another thing I observed from the npm log

`Considering PhantomJS found at C:\Program Files (x86)\nodist\bin\phantomjs.CMD
Found PhantomJS at C:\Program Files (x86)\nodist\bin\phantomjs.CMD ...verifying
Error verifying phantomjs, continuing { [Error: Command failed: C:\Program Files (x86)\nodist\bin\phantomjs.CMD --version`
 

it is trying to run the phantomjs.CMD --version which also failing 

```
Error verifying phantomjs, continuing { [Error: Command failed: C:\Program Files (x86)\nodist\bin\phantomjs.CMD --versio
n
internal/child_process.js:274
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:362:9)
    at Object.<anonymous> (C:\Program Files (x86)\nodist\bin\node_modules\phantomjs-prebuilt\bin\phantomjs:22:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Program Files (x86)\\nodist\\bin\\phantomjs.CMD --version' }
```

Following are the versions i have 
`
D:\PROJECTS\sbc-web\app>node -v   
v5.5.0  

D:\PROJECTS\sbc-web\app>npm -v   
3.10.9  

D:\PROJECTS\sbc-web\app>phantomjs -v   
2.1.1   
`
I also tried to install pahntomjs by directly downloading the repo and installing,That also is getting the error 

npm ERR! phantomjs-prebuilt@2.1.13 install: `node install.js`

**Comment by audduk** [comment]
See Try an advice of @galtenhofen (see issue #644)
npm set strict-ssl false

**Comment by gtsarenkov** [comment]
I'm seeing this issue under Jenkins 2 Pipeline project (Jenkins is running under Windows 2008R2 64bits as a service). PhantomJS is failing only when executing with --version when checking correctness of installation. In the same Pipeline phantomjs executes ember-cli tests without any problem. I'm guessing there is an issue with availability of the console to print a version when running under Windows service.
