### ISSUE TITLE
upgraded to Node 6  failing on SyntaxError: Unexpected token >     at Module._compile (module.js:439:25)

### ISSUE THREAD

**Issue by jlevym** [Medium/phantomjs#657]
we have the following error after upgrading our application to node 6

    SyntaxError: Unexpected token >  at Module._compile (module.js:439:25)

and in our process.error log we see the following:

    package/node_modules/phantom/lib/index.js:23
    return new Promise(resolve => resolve(new _phantom2.default(args, config)));

i see in my local repo that i have both phantomjs and phantomjs-rebuilt and that this problematic code is in the phantomjs. It seems that the  production app only has the phantomjs, but none of this is clear to me

can you help explain what has caused this to appear and how to solve it

**Comment by jlevym** [comment]
this problem is related to the version used in phantom, not phantomjs
