### ISSUE TITLE
.path fails when installed with yarn

### ISSUE THREAD

**Issue by balupton** [Medium/phantomjs#671]
```
$ yarn --version
0.19.1

$ yarn add --dev phantomjs-prebuilt

$ node
>  require('phantomjs-prebuilt').path
'/Users/balupton/bin/phantomjs'

$ ./node_modules/.bin/phantomjs
Error executing phantom at /Users/balupton/bin/phantomjs
Error: spawn /Users/balupton/bin/phantomjs ENOENT
    at exports._errnoException (util.js:1023:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

$ npm install --save-dev phantomjs-prebuilt

$ node
> require('phantomjs-prebuilt').path
'/Users/balupton/Projects/ember/ember-cli-pagination/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs'

$ ./node_modules/.bin/phantomjs
phantomjs> ^C
```

**Comment by csvan** [comment]
I have a dependency on 2.1.14, and trying to run `yarn install` (v0.20.3) yields the following:

```
[INFO] [4/4] Building fresh packages...
[ERROR] error /opt/balthazar/workdir/web/node_modules/phantomjs: Command failed.
[ERROR] Exit code: 1
[ERROR] Command: sh
[ERROR] Arguments: -c node install.js
[ERROR] Directory: /opt/balthazar/workdir/web/node_modules/phantomjs
[ERROR] Output:
[ERROR] PhantomJS not found on PATH
[ERROR] Phantom installation failed TypeError: Path must be a string. Received undefined
[ERROR]     at assertPath (path.js:7:11)
[ERROR]     at Object.join (path.js:1211:7)
[ERROR]     at findSuitableTempDirectory (/opt/balthazar/workdir/web/node_modules/phantomjs/install.js:127:30)
[ERROR]     at /opt/balthazar/workdir/web/node_modules/phantomjs/install.js:476:19
[ERROR]     at nextTickCallback (/opt/balthazar/workdir/web/node_modules/kew/kew.js:47:28)
[ERROR]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[ERROR]     at process._tickCallback (internal/process/next_tick.js:98:9) TypeError: Path must be a string. Received undefined
[ERROR]     at assertPath (path.js:7:11)
[ERROR]     at Object.join (path.js:1211:7)
[ERROR]     at findSuitableTempDirectory (/opt/balthazar/workdir/web/node_modules/phantomjs/install.js:127:30)
[ERROR]     at /opt/balthazar/workdir/web/node_modules/phantomjs/install.js:476:19
[ERROR]     at nextTickCallback (/opt/balthazar/workdir/web/node_modules/kew/kew.js:47:28)
[ERROR]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[ERROR]     at process._tickCallback (internal/process/next_tick.js:98:9)
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

If its of any help, I can only reproduce this under Linux. On Windows 7 (Cygwin) it works fine.

**Comment by csvan** [comment]
Related: https://github.com/yarnpkg/yarn/issues/1016
