### ISSUE TITLE
PhantomJS Fundamentally Broken on Mac

### ISSUE THREAD

**Issue by PatriotRDX** [Medium/phantomjs#675]
I tried to install the [Foundation for Emails 2 stack](http://foundation.zurb.com/emails/docs/sass-guide.html) from Terminal. One component failed. PhantomJS. Seeing as this thread is full of the same report by hundreds of others, I contacted Zurb. They suggested cd'ing to the folder I was installing the stack to and running this command: `npm install phantomjs-prebuilt`.

I received the same error as before.

Here's a log of the command line process. I've also included the debug file attached. It's in a [Google Drive link](https://drive.google.com/file/d/0Bw8JHb7a8jjEVTJTUTNXbXJ6N1k/view?usp=sharing) because GitHub can't handle .log files.

```Last login: Tue Feb 28 13:20:21 on ttys000
COM-WALLAC638L1:~ wallace.638$ cd Documents
COM-WALLAC638L1:Documents wallace.638$ cd RightClick
COM-WALLAC638L1:RightClick wallace.638$ npm install phantomjs-prebuilt

> phantomjs-prebuilt@2.1.14 install /Users/wallace.638/Documents/RightClick/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip
Saving to /var/folders/mm/s4dpb_wd61qdxnk50_5rz5sckl4jps/T/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...

Error making request.
Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1117:19)
    at Object.onceWrapper (events.js:291:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Please report this full log at https://github.com/Medium/phantomjs
foundation-emails-template@1.0.0 /Users/wallace.638/Documents/RightClick
└─┬ gulp-mail@0.1.2
  └─┬ nodemailer@0.7.1
    └─┬ mailcomposer@0.2.12
      └─┬ follow-redirects@0.0.3
        └── underscore@1.8.3 

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "install" "phantomjs-prebuilt"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wallace.638/Documents/RightClick/npm-debug.log
COM-WALLAC638L1:RightClick wallace.638$ exit
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by NicolasPelletier** [comment]
It seems Amazon S3 is down: http://status.aws.amazon.com/. That might be the cause of the problem.

When I tried to go to https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip to download it myself, I saw an Amazon S3 error.

**Comment by PatriotRDX** [comment]
@NicolasPelletier thanks for the reply... I did just see that on Reddit. Hopefully it will be back up soon. I guess this issue needs to be closed then.
