### ISSUE TITLE
npm install v2.1.14 fails due to invalid internal CDN reference

### ISSUE THREAD

**Issue by denver-HJS** [Medium/phantomjs#677]
When I run `npm install phantomjs-prebuilt@2.1.14` the command fails when it tries to execute the Node command `node install.js`

I tracked the issue down to a CDN reference that no longer exists in */lib/util.js*

Line 14: `var DEFAULT_CDN = 'https://github.com/Medium/phantomjs/releases/download/v2.1.1' `

If you go to this URL it returns a 404 now - can this value be updated?

```
C:\src\my-project-dir>npm install

> phantomjs-prebuilt@2.1.14 install C:\src\my-project-dir\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to C:\Users\BOHLIN~1.DEN\AppData\Local\Temp\1\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...

Error making request.
Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\src\my-project-dir\npm-debug.log
```

**Comment by diegoconcha** [comment]
I was able to get this working via:
https://github.com/Medium/phantomjs/issues/674#issuecomment-283150753

**Comment by denver-HJS** [comment]
That's an awesome fix for now, thanks for the heads up!

**Comment by denver-HJS** [comment]
Closing since this was an AWS outage related issue that's been resolved.
