### ISSUE TITLE
Error making request.

### ISSUE THREAD

**Issue by pswen** [Medium/phantomjs#690]
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /root/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: connect ETIMEDOUT
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by pswen** [comment]
system:
Linux  2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 00:57:44 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by xiaohp** [comment]
see this https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout
