### ISSUE TITLE
 Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.

### ISSUE THREAD

**Issue by pdbi** [Medium/phantomjs#695]
Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR![ Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.](url)
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by erdiegoant** [comment]
Getting same error here,
node v7.7.4
npm v4.1.2

**Comment by Trim21** [comment]
windows user same problem.
solved by installing again..

**Comment by Xisabla** [comment]
Same error on a Raspberry Pi 3

![Screen](https://puu.sh/vIeLs/536ba25d51.png)

**Comment by widget-** [comment]
Maybe same issue here. Failed on an automated build Saturday night, but worked again Sunday night. It gave this before the normal npm ERR "not our fault" stuff.

```
Error making request.
Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
```

**Comment by KathrynCrawford** [comment]
Same issue here. Tried to just install phantomjs directly, but I got the same error.

> npm ERR! Darwin 16.5.0
> npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "install" "--save" "critical"
> npm ERR! node v7.10.0
> npm ERR! npm  v4.2.0
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> 
> npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node install.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs phantomjs-prebuilt
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls phantomjs-prebuilt
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/kathryn.crawford/.npm/_logs/2017-05-15T18_06_05_440Z-debug.log

**Comment by ss89** [comment]
Same issue (armv7) :
npm ERR! Linux 3.8.13.30
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1

**Comment by gygesM** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_m
odules\fsevents):                                                                            
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted
 {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})                         
npm WARN karma-sinon-chai@1.3.1 requires a peer of sinon@^2.1.0 but none was installed.      
npm ERR! code ELIFECYCLE                                                                     
npm ERR! errno 1                                                                             
npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`                                
npm ERR! Exit status 1                                                                       
npm ERR!                                                                                     
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.           
npm ERR! Make sure you have the latest version of node.js and npm installed.                 
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,       
npm ERR! not with npm itself.                                                                
npm ERR! Tell the author that this fails on your system:                                     
npm ERR!     node install.js                                                                 
npm ERR! You can get information on how to open an issue for this project with:              
npm ERR!     npm bugs phantomjs-prebuilt                                                     
npm ERR! Or if that isn't available, you can get their info via:                             
npm ERR!     npm owner ls phantomjs-prebuilt                                                 
npm ERR! There is likely additional logging output above.                                    
                                                                                             
npm ERR! A complete log of this run can be found in:                                         
npm ERR!     C:\Users\Gyges\AppData\Roaming\npm-cache\_logs\2017-05-27T18_22_53_651Z-debug.lo
g

**Comment by ceoaliongroo** [comment]
Also i have this error, update node last version.

I downloaded the phantomjs binary version, but still i have the same error.

Any idea what is the error? i can understand, what is exactly the error.
Maybe how to debug `node install.js`

**Comment by cynicXer** [comment]
Same error with Ubuntu 16.04 LTS.
`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm ERR! Linux 4.4.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cynicxer/juice-shop/npm-debug.log`

**Comment by babacs** [comment]
Hi, 
same error here:
m ERR! Linux 3.8.0-35-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

**Comment by matuschewski-schulze** [comment]
FYI, i had the same issue. Turns out, i did not have the PATH set and this error occured.
Most likely because this package needs tar and bzip2.
So, please check you environment just before the installation.
