### ISSUE TITLE
Failed to install, Can you help me with it?

### ISSUE THREAD

**Issue by tianwenwen** [Medium/phantomjs#702]
Downloading https://github.com/Medium/phantomjs/releases/download/v2
js-2.1.1-windows.zip
Saving to C:\Users\Lanxumit\AppData\Local\Temp\phantomjs\phantomjs-2
.zip
Receiving...
|
Error making request.
Error: connect ETIMEDOUT 54.231.82.178:443
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
 node v4.4.4
 npm  v2.15.1
 phantomjs-prebuilt@2.1.14 install: `node install.js`
 Exit status 1

 Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.j

 This is most likely a problem with the phantomjs-prebuilt package,

**Comment by tianwenwen** [comment]
node v4.4.4
 npm  v2.15.1

**Comment by tianwenwen** [comment]
phantomjs-prebuilt@2.1.14 install: `node install.js`
 Exit status 1

 Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.j

 This is most likely a problem with the phantomjs-prebuilt package,

**Comment by tianwenwen** [comment]
#674 (comment)

**Comment by tianwenwen** [comment]
https://github.com/Medium/phantomjs/issues/674#issuecomment-283150753

**Comment by Charchit26** [comment]
Hi @
