### ISSUE TITLE
error insall

### ISSUE THREAD

**Issue by hduwyz** [Medium/phantomjs#711]
126432 verbose stack     at emitTwo (events.js:106:13)
126432 verbose stack     at ChildProcess.emit (events.js:191:7)
126432 verbose stack     at maybeClose (internal/child_process.js:886:16)
126432 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
126433 verbose pkgid phantomjs-prebuilt@2.1.14
126434 verbose cwd E:\workspace\tairanchina\vue2-manage
126435 verbose Windows_NT 6.1.7601
126436 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hzwyz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
126437 verbose node v6.10.2
126438 verbose npm  v4.5.0
126439 error code ELIFECYCLE
126440 error errno 1
126441 error phantomjs-prebuilt@2.1.14 install: `node install.js`
126441 error Exit status 1
126442 error Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
126442 error Make sure you have the latest version of node.js and npm installed.
126442 error If you do, this is most likely a problem with the phantomjs-prebuilt package,
126442 error not with npm itself.
126442 error Tell the author that this fails on your system:
126442 error     node install.js
126442 error You can get information on how to open an issue for this project with:
126442 error     npm bugs phantomjs-prebuilt
126442 error Or if that isn't available, you can get their info via:
126442 error     npm owner ls phantomjs-prebuilt
126442 error There is likely additional logging output above.
126443 verbose exit [ 1, true ]

**Comment by riveryong** [comment]
I have receive same messages when install it
