### ISSUE TITLE
Error: read ECONNRESET while upgrade jhipster 4.5.3 to 4.5.5

### ISSUE THREAD

**Issue by pkmyl** [Medium/phantomjs#717]
Please find the below logs for the reference,

Current code has been generated with version 4.5.3
Updating generator-jhipster to 4.5.5 . This might take some time...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! Something went wrong while updating JHipster! yarn add v0.24.6
[1/4] Resolving packages...
[2/4] Fetching packages...
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
 warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
warning "angular2-cookie@1.2.6" has incorrect peer dependency "@angular/common@^2.0.0".
warning "angular2-cookie@1.2.6" has incorrect peer dependency "@angular/core@^2.0.0".
warning "ng2-translate@4.2.0" has incorrect peer dependency "@angular/core@^2.0.0".
warning "ng2-translate@4.2.0" has incorrect peer dependency "@angular/http@^2.0.0".
error /Userdisk/Source/jhipster-projects/casestudy/node_modules/phantomjs-prebuilt: Command failed.
Exit code: 1
Command: sh
Arguments: -c node install.js
Directory: /Userdisk/Source/jhipster-projects/casestudy/node_modules/phantomjs-prebuilt
Output:
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TLSWrap.onread (net.js:572:26)

Please report this full log at https://github.com/Medium/phantomjs

    at Environment.error (/home/praveenkumar/.config/yarn/global/node_modules/yeoman-environment/lib/environment.js:89:38)
    at constructor.error (/home/praveenkumar/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base.js:1561:18)
    at shelljs.exec (/home/praveenkumar/.config/yarn/global/node_modules/generator-jhipster/generators/upgrade/index.js:265:27)
    at /home/praveenkumar/.config/yarn/global/node_modules/shelljs/src/exec.js:204:9
    at ChildProcess.exithandler (child_process.js:211:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)

**Comment by devanonym** [comment]
the same result
