### ISSUE TITLE
Error: getaddrinfo ENOTFOUND github-production-release-asset-2e65be.s3.amazonaws.com

### ISSUE THREAD

**Issue by rally25rs** [Medium/phantomjs#718]
Error running the command:
> npm install phantomjs-prebuilt@2.1.14

```
11:46:06 Now using node v6.3.0 (npm v3.10.3)
11:46:31 
11:46:31 > phantomjs-prebuilt@2.1.14 install /var/lib/jenkins/jobs/ui-components-v3/workspace/node_modules/phantomjs-prebuilt
11:46:31 > node install.js
11:46:31 
11:46:32 PhantomJS not found on PATH
11:46:32 Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
11:46:32 Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
11:46:32 Receiving...
11:46:51 
11:46:51 Error making request.
11:46:51 Error: getaddrinfo ENOTFOUND github-production-release-asset-2e65be.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com:443
11:46:51     at errnoException (dns.js:28:10)
11:46:51     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
11:46:51 
11:46:51 Please report this full log at https://github.com/Medium/phantomjs
11:46:52 npm ERR! Linux 3.2.0-23-generic
11:46:52 npm ERR! argv "/var/lib/jenkins/.nvm/versions/node/v6.3.0/bin/node" "/var/lib/jenkins/.nvm/versions/node/v6.3.0/bin/npm" "install" "phantomjs-prebuilt@2.1.14"
11:46:52 npm ERR! node v6.3.0
11:46:52 npm ERR! npm  v3.10.3
11:46:52 npm ERR! code ELIFECYCLE
11:46:52 
11:46:52 npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
11:46:52 npm ERR! Exit status 1
11:46:52 npm ERR! 
11:46:52 npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
```

**Comment by rally25rs** [comment]
DNS issue on my end. Closing this.

**Comment by widget-** [comment]
I've ran into this probably 10 times by now. It would be nice if some sort of auto-retry could be added.

**Comment by ish3lan** [comment]
I faced the same problem here.

**Comment by MukundhanSampath** [comment]
oh god.. Auto ethernet will do the trick
