### ISSUE TITLE
PhantomJS not found on PATH

### ISSUE THREAD

**Issue by Zappjcdecaux** [Medium/phantomjs#722]
Hi everyone,
We had projects building on a Jenkins Slave server, and using phantomJS
Until last week, everythink worked fine

**Comment by Hal-pan** [comment]
I also met

**Comment by shgattu** [comment]
I have same issues

**Comment by Grox-Ni** [comment]
same issue

**Comment by LarsVonQualen** [comment]
How is this even a problem? Does anyone know why Chrome for instance is flagging the url? It's basically just a redirect to Amazon S3, so is the problem S3? Is it flagged because someone uses Github to distribute malware, and then as a consequence other assets from different projects is also flagged?

It's really annoying because it have broken our CI environment :D

**Comment by szelpe** [comment]
Please let me know if you have a solution for this issue as it breaks our CI build as well :\

**Comment by dave000** [comment]
We found the quick fix for the issue by overriding the PHANTOMJS_CDNURL env variable and setting it to our own URL. You can also use any URL here. 
This is the default CDN Url: https://github.com/Medium/phantomjs/releases/download/v2.1.1/ and the install.js adds phantomjs-2.1.1-windows.zip to the end.
So if you override the env variable like https://myOwnRepoUrl.com/folder and you have the content here https://myOwnRepoUrl.com/folder/phantomjs-2.1.1-windows.zip it should work.

**Comment by kuangcaibao** [comment]
[this works for me](https://github.com/xhlwill/blog/issues/11)

**Comment by JoeKahl** [comment]
C:\Users\jkahl1\Source\Repos\digital-advisor-fe>npm install

> phantomjs-prebuilt@2.1.14 install C:\Users\jkahl1\Source\Repos\digital-advisor-fe\node_modules\karma-phantomjs-launcher\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to C:\Users\jkahl1\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...

Error making request.
Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jkahl1\AppData\Roaming\npm-cache\_logs\2017-08-23T13_58_46_334Z-debug.log

**Comment by ruiqiliu** [comment]
Adding PhantomJS to PATH manually solved this problem: 
 download [PhantomJS](https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip) manually, and unzip it, then add phantomjs.exe to the PATH env varibable.

**Comment by nhack** [comment]
I'm having the same issue, any luck solving it?

**Comment by JoeKahl** [comment]
My solution is to manually download the zip and place it in the location the script expects.
Just read the error message carefully to find the expected path.

**Comment by nhack** [comment]
But the issue is really strange, because everything used to work fine, and suddenly the install.js script says phantomjs can't be found in the path, but phantomjs is there:
>`which phantomjs`
-> `/dev/node_modules/phantomjs/lib/phantom/bin/phantomjs`

**Comment by anuluvi** [comment]
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to C:\Users\user01\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip

reinstall globally.

**Comment by dhruvdutt** [comment]
For Linux, just ran this script and it worked.

```
cd /usr/local/share
sudo wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
sudo tar xjf phantomjs-2.1.1-linux-x86_64.tar.bz2
sudo ln -s /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/share/phantomjs
sudo ln -s /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
sudo ln -s /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/bin/phantomjs
```

**Comment by klrmn** [comment]
now, granted, i **also** did @dhruvdutt 's global install of phantomjs, but that didn't fix it.
what fixed it was to define TMPDIR=/tmp before running install. the problem was that 
process.env.TMPDIR was resolving to null rather than a string.

**Comment by VictorJSV** [comment]
By @diegoconcha

Create an .npmrc in my root project folder and added this to it:
phantomjs_cdnurl=https://cnpmjs.org/downloads
Now phantomjs installs fine via npm.

Duplicate of #674

it works!

**Comment by woozhijun** [comment]
RUN PHANTOMJS_CDNURL=https://npm.taobao.org/mirrors/phantomjs/ npm install phantomjs-prebuilt

**Comment by doniz** [comment]
For me helps to install `bzip2` with `yum install bzip2` on centos machine.

**Comment by prithvirajrmd2015** [comment]
Hi every i too got the same the crazy thing is my office network is blocking my connection to that repository... ;- )
