### ISSUE TITLE
All prebuilt release links are dead

### ISSUE THREAD

**Issue by McOffsky** [Medium/phantomjs#729]
All links are dead since today. Hence installation from npm is impossible.

https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip
https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-i686.tar.bz2

**Comment by Orekhov** [comment]
Same happens with some other repositories on github. Looks like a global issue.

**Comment by McOffsky** [comment]
Phantom JS was the only one that was causing problems for me, hence my post here. I will try to contact github, this issue can be closed.

**Comment by danrigsby** [comment]
Please post here if we find any additional issues we can follow or work arounds

**Comment by rudnitskih** [comment]
We have the same problem also with https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-48_binding.node

**Comment by Orekhov** [comment]
A reply from github team that I just received: 
> Our team is currently working to resolve a known issue with release downloads that began earlier today.

**Comment by swilliamset** [comment]
My resource files are successfully downloading again 
https://github.com/Medium/phantomjs/releases/tag/v2.1.1

**Comment by jperasmus** [comment]
Did someone forget to renew their Let's Encrypt SSL certificates? 😜

**Comment by Orekhov** [comment]
Works for me as well.
I believe, this issue can be closed now.

**Comment by sacr3dc0w** [comment]
Still getting issues.

```
Error making request.
Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1013:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
    at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)

Please report this full log at https://github.com/Medium/phantomjs
```
