### ISSUE TITLE
error

### ISSUE THREAD

**Issue by keshiim** [Medium/phantomjs#734]
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> phantomjs@2.1.7 install /Users/Jason/Downloads/phantomjs-master/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-macosx.zip
Saving to /var/folders/jc/czyzwx2d27j87wy7m14gjf7m0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Using proxy http://login:******@host/:port
Receiving...

Error making request.
Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND host host:80
    at ClientRequest.onError (/Users/Jason/Downloads/phantomjs-master/node_modules/tunnel-agent/index.js:176:17)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1025:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Please report this full log at https://github.com/Medium/phantomjs
phantomjs-prebuilt@2.1.15 /Users/Jason/Downloads/phantomjs-master
└── g@2.0.1 
npm ERR! Darwin 17.0.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "install" "phantomjs" "g"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@2.1.7 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Jason/Downloads/phantomjs-master/npm-debug.log

**Comment by NoBugsss** [comment]
+1

**Comment by keshiim** [comment]
I resolve it by download it directly. And config the `Path`，So it works

**Comment by NoBugsss** [comment]
thanks

At 2017-08-15 14:56:51, "Jason zheng(郑明君)" <notifications@github.com> wrote:


I resolve it by download it directly. And config the Path，So it works
