### ISSUE TITLE
Error while installing with NPM

### ISSUE THREAD

**Issue by egroJ97** [Medium/phantomjs#737]
[npm-debug-log.txt](https://github.com/Medium/phantomjs/files/1244025/npm-debug-log.txt)

It says this after trying to install Phantom.js, don't know what to do, help.

**Comment by JoeKahl** [comment]
Below is my issue.  Not sure if it is related:


C:\Users\jkahl1\Source\Repos\digital-advisor-fe>npm install

> phantomjs-prebuilt@2.1.14 install C:\Users\jkahl1\Source\Repos\digital-advisor-fe\node_modules\karma-phantomjs-launcher\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to C:\Users\jkahl1\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...

Error making request.
Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jkahl1\AppData\Roaming\npm-cache\_logs\2017-08-23T13_58_46_334Z-debug.log

**Comment by babusona-kgp** [comment]
Facing same issue. Attaching the log.

[npm-debug.log](https://github.com/Medium/phantomjs/files/1513081/npm-debug.log)
