### ISSUE TITLE
Yarn failed downloading PhantomJS

### ISSUE THREAD

**Issue by ImperfektDaemon** [Medium/phantomjs#738]
error C:\Projects\Ecommerce\SaleorDemo\saleor\node_modules\phantomjs-prebuilt: Command failed.
Exit code: 1
Command: C:\windows\system32\cmd.exe
Arguments: /d /s /c node install.js
Directory: C:\Projects\Ecommerce\SaleorDemo\saleor\node_modules\phantomjs-prebuilt
Output:
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to C:\Users\<Username>\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip

Receiving...

Error making request.
Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TLSWrap.onread (net.js:568:26)

Please report this full log at https://github.com/Medium/phantomjs info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by douxc** [comment]
1、download ```https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip```  by yourself;
2、move the zip file you download to ```C:\Users<Username>\AppData\Local\Temp\phantomjs\```;
3、reinstall

**Comment by madsobel** [comment]
@douxc I suppose that works fine when you're on a local environment. But not if you have a build server that tries to install using yarn.

**Comment by marvinhagemeister** [comment]
Just happened again today for me.

**Comment by codeprefect** [comment]
This is also                                           happening in a docker environment
