### ISSUE TITLE
Failed at the phantomjs-prebuilt@2.1.99 install script 'node install.js'.

### ISSUE THREAD

**Issue by Santhoshas** [Medium/phantomjs#739]
node v6.11.3
 npm  v3.10.10

NAME="CentOS Linux"
VERSION="7 (Core)"

npm ERR! Linux 3.10.0-514.26.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.99 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.99 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cloud-user/testGit/cast-auth/cast-auth-demo-ui/npm-debug.log

**Comment by Shpiller** [comment]
I have the same
`Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:606:25)

Please report this full log at https://github.com/Medium/phantomjs
npm info lifecycle phantomjs-prebuilt@2.1.15~install: Failed to exec install script
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.15 install: `node install.js`
npm ERR! Exit status 1
`

**Comment by hwinn4** [comment]
I am encountering the same error when running `npm install phantomjs-prebuilt` as part of my CI build on Codeship:

/node_modules/phantomjs-prebuilt/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/home/rof/src/github.com/fuigo/fuigo-web/node_modules/phantomjs-prebuilt/node_modules/request/node_modules/hawk/lib/index.js:5:33)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/home/rof/.nvm/v0.10.48/bin/node" "/home/rof/.nvm/v0.10.48/bin/npm" "install" "phantomjs-prebuilt"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script 'node install.js'.

**Comment by hwinn4** [comment]
Update: I was able to resolve the issue with `node install.js` by running `nvm install 8.9.0` (the current recommended version of node) prior to running `npm install phantomjs-prebuilt`.

**Comment by maxzaselian-okta** [comment]
I've got same issue on CentOS Linux 7
node v5.6.0
npm v3.9.6

$ sudo npm install phantomjs-prebuilt

> phantomjs-prebuilt@2.1.16 install /home/vagrant/nap_1/nap/node_modules/phantomjs-prebuilt
> node install.js

/home/vagrant/nap_1/nap/node_modules/phantomjs-prebuilt/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vagrant/nap_1/nap/node_modules/phantomjs-prebuilt/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm WARN OktaPlugin@0.0.4 No repository field.
npm WARN OktaPlugin@0.0.4 No license field.
npm ERR! Linux 3.10.0-327.18.2.el7.x86_64
npm ERR! argv "node" "/bin/npm" "install" "phantomjs-prebuilt"
npm ERR! node v0.12.9
npm ERR! npm  v3.9.6
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/nap_1/nap/npm-debug.log

**Comment by rvolosatovs** [comment]
https://github.com/Medium/phantomjs/issues/756

**Comment by erdemapaydin** [comment]
updating the node/npm versions did not help for me - same error persists.

**Comment by han8gui** [comment]
npm update
npm install

**Comment by ayelen117** [comment]
What worked for me for phantomjs-prebuilt@2.1.16. was to:

- uninstall npm 
- [install nvm](https://github.com/creationix/nvm/blob/master/README.md#installation)
- run: `nvm install 8.9.0`

Now I have node version 8.9.0 and npm version 5.5.1.

Good luck!

**Comment by FizzBuzz791** [comment]
This is occurring in TravisCI, so the above solutions are not feasible unfortunately.

**Comment by webster** [comment]
What worked for me:
* Install nvm using curl install script from https://nvm.sh/
* `nvm install 8.9.0`
* `npm install`
