### ISSUE TITLE
tunneling socket could not be established, cause=connect ECONNREFUSED

### ISSUE THREAD

**Issue by lhwu** [Medium/phantomjs#750]
PhantomJS not found on PATH
Downloading https://npm.taobao.org/mirrors/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:37295
    at ClientRequest.onError (/home/bottle/workspace/Followup_Frontend/node_modules/_tunnel-agent@0.6.0@tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by rvolosatovs** [comment]
I also had problems with this version, for me the issue was that neither github nor bitbucket CDNs actually work.
I had to download from http://cnpmjs.org/downloads.
Try 
```bash
sed -i'' -e '/^phantomjs_cdnurl=/d' ~/.npmrc && echo 'phantomjs_cdnurl=http://cnpmjs.org/downloads' >> ~/.npmrc 
```

**Comment by rvolosatovs** [comment]
https://github.com/Medium/phantomjs/issues/756
