### ISSUE TITLE
I can't install reportjs which it needs phantomjs

### ISSUE THREAD

**Issue by mahdi-gh1373** [Medium/phantomjs#754]
when I want to install reportjs i see something like this :
```
> phantomjs@1.9.15 install I:\Projects\jsreport\first-test\node_modules\jsreport-import-export\node_modules\phantomjs
> node install.js

invalid config loglevel="notice"
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to C:\Users\M7402~1.GHO\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...

Error making request.
Error: connect ETIMEDOUT 104.192.143.3:443
    at Object._errnoException (util.js:1019:11)
    at _exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN enoent ENOENT: no such file or directory, open 'I:\Projects\jsreport\first-test\package.json'
npm WARN react-copy-to-clipboard@4.3.0 requires a peer of react@^0.14 || ^15 but none was installed.
npm WARN first-test No description
npm WARN first-test No repository field.
npm WARN first-test No README data
npm WARN first-test No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@1.9.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\m.gholizadeh\AppData\Roaming\npm-cache\_logs\2017-11-04T09_27_46_189Z-debug.log

I:\Projects\jsreport\first-test>npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...
```

**Comment by rvolosatovs** [comment]
can be related https://github.com/Medium/phantomjs/issues/756
