### ISSUE TITLE
NPM install fails for version 2.1.1

### ISSUE THREAD

**Issue by rvolosatovs** [Medium/phantomjs#756]
```sh
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: write EPROTO 140214257649472:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:825:

    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)
```
Encountered this issue when trying to `npm install` a new project.
Both Bitbucket and Github CDNs seem to not contain this version. Fixed by setting the `phantomjs_cdnurl` as explained in [documentation](https://github.com/Medium/phantomjs#deciding-where-to-get-phantomjs) to http://cnpmjs.org/downloads.

Try:
```shell
sed -i'' -e '/^phantomjs_cdnurl=/d' ~/.npmrc && echo 'phantomjs_cdnurl=http://cnpmjs.org/downloads' >> ~/.npmrc
```

**Comment by yowainwright** [comment]
@rvolosatovs this worked for me.

**Comment by de1ck** [comment]
@rvolosatovs @yowainwright 
about  this release v2.1.1 `https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip`
base for : `https://github.com/Medium/phantomjs/releases?after=v2.1.5`
This is because the file phantomjs-2.1.1-linux-x86_64.tar.bz2 is too large, and the network is not easy to download and fail.
you can Manually download it save  into  your linux path /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
[download link](http://phantomjs.org/download.htmll)
