### ISSUE TITLE
fatal: reference is not a tree

### ISSUE THREAD

**Issue by BryanCrotaz** [Medium/phantomjs#766]
npm i --save-dev phantomjs-prebuilt
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git checkout 13d1672ac6d8ec446720b110e18956befdad1823
npm ERR! fatal: reference is not a tree: 13d1672ac6d8ec446720b110e18956befdad1823
npm ERR! 

Seeing this in CI and on MacOS desktop

**Comment by BryanCrotaz** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '--save-dev',
1 verbose cli   'phantomjs-prebuilt@2.1.14' ]
2 info using npm@5.6.0
3 info using node@v8.9.1
4 verbose npm-session 83ec4cf200a4ddb4
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/phantomjs-prebuilt 95ms (from cache)
8 silly pacote version manifest for phantomjs-prebuilt@2.1.14 fetched in 123ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly fetchPackageMetaData error for ember-cli-app-version@github:BryanCrotaz/ember-cli-app-version#13d1672ac6d8ec446720b110e18956befdad1823 Command failed: /usr/bin/git checkout 13d1672ac6d8ec446720b110e18956befdad1823
12 silly fetchPackageMetaData fatal: reference is not a tree: 13d1672ac6d8ec446720b110e18956befdad1823
13 silly saveTree sc-pp-frontend@1.3.6
13 silly saveTree ├─┬ awsmqtt@0.0.1
13 silly saveTree │ ├── crypto-js@3.1.8
13 silly saveTree │ ├─┬ ember-cli-babel@5.2.4
13 silly saveTree │ │ ├─┬ broccoli-babel-transpiler@5.7.2
13 silly saveTree │ │ │ ├─┬ babel-core@5.8.38
13 silly saveTree │ │ │ │ ├── babel-plugin-constant-folding@1.0.1
13 silly saveTree │ │ │ │ ├── babel-plugin-dead-code-elimination@1.0.2
13 silly saveTree │ │ │ │ ├── babel-plugin-eval@1.0.1
13 silly saveTree │ │ │ │ ├── babel-plugin-inline-environment-variables@1.0.1
13 silly saveTree │ │ │ │ ├── babel-plugin-jscript@1.0.4
13 silly saveTree │ │ │ │ ├── babel-plugin-member-expression-literals@1.0.1
13 silly saveTree │ │ │ │ ├── babel-plugin-property-literals@1.0.1
13 silly saveTree │ │ │ │ ├── babel-plugin-proto-to-assign@1.0.4
13 silly saveTree │ │ │ │ ├── babel-plugin-react-constant-elements@1.0.3
13 silly saveTree │ │ │ │ ├── babel-plugin-react-display-name@1.0.3
13 silly saveTree │ │ │ │ ├── babel-plugin-remove-console@1.0.1
13 silly saveTree │ │ │ │ ├── babel-plugin-remove-debugger@1.0.1
13 silly saveTree │ │ │ │ ├── babel-plugin-runtime@1.0.7
13 silly saveTree │ │ │ │ ├── babel-plugin-undeclared-variables-check@1.0.2
13 silly saveTree │ │ │ │ ├── babel-plugin-undefined-to-void@1.1.6
13 silly saveTree │ │ │ │ ├── babylon@5.8.38
13 silly saveTree │ │ │ │ ├── bluebird@2.11.0
13 silly saveTree │ │ │ │ ├─┬ chalk@1.1.3
13 silly saveTree │ │ │ │ │ └── ansi-styles@2.2.1
13 silly saveTree │ │ │ │ ├── convert-source-map@1.5.0
13 silly saveTree │ │ │ │ ├── core-js@1.2.7
13 silly saveTree │ │ │ │ ├── debug@2.6.8
13 silly saveTree │ │ │ │ └── detect-indent@3.0.1
13 silly saveTree │ │ │ ├─┬ broccoli-funnel@1.2.0
13 silly saveTree │ │ │ │ ├── array-equal@1.0.0
13 silly saveTree │ │ │ │ ├── blank-object@1.0.2
13 silly saveTree │ │ │ │ ├── broccoli-plugin@1.3.0
13 silly saveTree │ │ │ │ └─┬ minimatch@3.0.4
13 silly saveTree │ │ │ │   └─┬ brace-expansion@1.1.8
13 silly saveTree │ │ │ │     ├── balanced-match@1.0.0
13 silly saveTree │ │ │ │     └── concat-map@0.0.1
13 silly saveTree │ │ │ ├─┬ broccoli-merge-trees@1.2.4
13 silly saveTree │ │ │ │ └── can-symlink@1.0.0
13 silly saveTree │ │ │ ├─┬ broccoli-persistent-filter@1.4.3
13 silly saveTree │ │ │ │ ├── async-disk-cache@1.3.2
13 silly saveTree │ │ │ │ └─┬ async-promise-queue@1.0.3
13 silly saveTree │ │ │ │   └─┬ async@2.5.0
13 silly saveTree │ │ │ │     └── lodash@4.17.4
13 silly saveTree │ │ │ └── clone@0.2.0
13 silly saveTree │ │ ├── broccoli-funnel@1.2.0
13 silly saveTree │ │ └── clone@2.1.1
13 silly saveTree │ └─┬ ember-cli-htmlbars@1.3.4
13 silly saveTree │   ├── broccoli-persistent-filter@1.3.1
13 silly saveTree │   └── strip-bom@2.0.0
13 silly saveTree ├─┬ broccoli-asset-rev@2.6.0
13 silly saveTree │ ├─┬ broccoli-asset-rewrite@1.1.0
13 silly saveTree │ │ └─┬ broccoli-filter@1.2.4
13 silly saveTree │ │   ├── broccoli-kitchen-sink-helpers@0.3.1
13 silly saveTree │ │   └── copy-dereference@1.0.0
13 silly saveTree │ ├── broccoli-filter@1.2.4
13 silly saveTree │ └── minimatch@3.0.4
13 silly saveTree ├── crypto-js@3.1.8
13 silly saveTree ├─┬ dynamic-link@0.2.3
13 silly saveTree │ └─┬ ember-getowner-polyfill@1.2.5
13 silly saveTree │   └── ember-cli-babel@5.2.4
13 silly saveTree ├── ember-ajax@3.0.0
13 silly saveTree ├─┬ ember-browserify@1.2.0
13 silly saveTree │ ├── acorn@5.2.1
13 silly saveTree │ ├── broccoli-caching-writer@3.0.3
13 silly saveTree │ ├─┬ browserify@13.3.0
13 silly saveTree │ │ ├── assert@1.4.1
13 silly saveTree │ │ ├─┬ browser-pack@6.0.2
13 silly saveTree │ │ │ ├─┬ combine-source-map@0.7.2
13 silly saveTree │ │ │ │ └── convert-source-map@1.1.3
13 silly saveTree │ │ │ ├── defined@1.0.0
13 silly saveTree │ │ │ └── JSONStream@1.3.1
13 silly saveTree │ │ ├─┬ browser-resolve@1.11.2
13 silly saveTree │ │ │ └── resolve@1.1.7
13 silly saveTree │ │ ├── browserify-zlib@0.1.4
13 silly saveTree │ │ ├─┬ buffer@4.9.1
13 silly saveTree │ │ │ └── base64-js@1.2.1
13 silly saveTree │ │ ├── cached-path-relative@1.0.1
13 silly saveTree │ │ ├─┬ concat-stream@1.5.2
13 silly saveTree │ │ │ └─┬ readable-stream@2.0.6
13 silly saveTree │ │ │   └── core-util-is@1.0.2
13 silly saveTree │ │ ├─┬ console-browserify@1.1.0
13 silly saveTree │ │ │ └── date-now@0.1.4
13 silly saveTree │ │ ├── constants-browserify@1.0.0
13 silly saveTree │ │ ├─┬ crypto-browserify@3.12.0
13 silly saveTree │ │ │ ├─┬ browserify-cipher@1.0.0
13 silly saveTree │ │ │ │ ├─┬ browserify-aes@1.1.1
13 silly saveTree │ │ │ │ │ ├── buffer-xor@1.0.3
13 silly saveTree │ │ │ │ │ ├── cipher-base@1.0.4
13 silly saveTree │ │ │ │ │ └── create-hash@1.1.3
13 silly saveTree │ │ │ │ └─┬ browserify-des@1.0.0
13 silly saveTree │ │ │ │   └── des.js@1.0.0
13 silly saveTree │ │ │ ├─┬ browserify-sign@4.0.4
13 silly saveTree │ │ │ │ ├── bn.js@4.11.8
13 silly saveTree │ │ │ │ ├── browserify-rsa@4.0.1
13 silly saveTree │ │ │ │ ├── create-hmac@1.1.6
13 silly saveTree │ │ │ │ └─┬ elliptic@6.4.0
13 silly saveTree │ │ │ │   └── brorand@1.1.0
13 silly saveTree │ │ │ ├── create-ecdh@4.0.0
13 silly saveTree │ │ │ ├── create-hash@1.1.3
13 silly saveTree │ │ │ ├── create-hmac@1.1.6
13 silly saveTree │ │ │ └── diffie-hellman@5.0.2
13 silly saveTree │ │ ├── defined@1.0.0
13 silly saveTree │ │ ├── deps-sort@2.0.0
13 silly saveTree │ │ ├── domain-browser@1.1.7
13 silly saveTree │ │ ├── duplexer2@0.1.4
13 silly saveTree │ │ ├─┬ glob@7.1.2
13 silly saveTree │ │ │ └── minimatch@3.0.4
13 silly saveTree │ │ └── JSONStream@1.3.1
13 silly saveTree │ ├── core-object@1.1.0
13 silly saveTree │ ├─┬ derequire@2.0.6
13 silly saveTree │ │ ├── acorn@4.0.13
13 silly saveTree │ │ └─┬ yargs@6.6.0
13 silly saveTree │ │   ├── camelcase@3.0.0
13 silly saveTree │ │   ├── cliui@3.2.0
13 silly saveTree │ │   └── decamelize@1.2.0
13 silly saveTree │ ├── lodash@4.17.4
13 silly saveTree │ └── walk-sync@0.2.7
13 silly saveTree ├─┬ ember-c3-shim@0.0.6
13 silly saveTree │ └── ember-cli-babel@5.2.4
13 silly saveTree ├─┬ ember-c3@0.3.1
13 silly saveTree │ └── ember-cli-babel@5.2.4
13 silly saveTree ├─┬ ember-can@0.8.5
13 silly saveTree │ └── ember-cli-babel@5.2.4
13 silly saveTree └─┬ ember-cli@2.16.2
13 silly saveTree   ├── amd-name-resolver@1.0.0
13 silly saveTree   ├─┬ babel-plugin-transform-es2015-modules-amd@6.24.1
13 silly saveTree   │ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.24.1
13 silly saveTree   │ │ ├─┬ babel-plugin-transform-strict-mode@6.24.1
13 silly saveTree   │ │ │ ├─┬ babel-runtime@6.23.0
13 silly saveTree   │ │ │ │ └── core-js@2.4.1
13 silly saveTree   │ │ │ └─┬ babel-types@6.25.0
13 silly saveTree   │ │ │   └── lodash@4.17.4
13 silly saveTree   │ │ ├── babel-runtime@6.23.0
13 silly saveTree   │ │ ├─┬ babel-template@6.25.0
13 silly saveTree   │ │ │ ├─┬ babel-traverse@6.25.0
13 silly saveTree   │ │ │ │ ├─┬ babel-code-frame@6.22.0
13 silly saveTree   │ │ │ │ │ └── js-tokens@3.0.1
13 silly saveTree   │ │ │ │ ├── babel-messages@6.23.0
13 silly saveTree   │ │ │ │ ├── babylon@6.17.4
13 silly saveTree   │ │ │ │ ├── globals@9.18.0
13 silly saveTree   │ │ │ │ └── lodash@4.17.4
13 silly saveTree   │ │ │ ├── babylon@6.17.4
13 silly saveTree   │ │ │ └── lodash@4.17.4
13 silly saveTree   │ │ └── babel-types@6.25.0
13 silly saveTree   │ ├── babel-runtime@6.23.0
13 silly saveTree   │ └── babel-template@6.25.0
13 silly saveTree   ├── bower-config@1.4.0
13 silly saveTree   ├── bower-endpoint-parser@0.2.2
13 silly saveTree   ├─┬ broccoli-babel-transpiler@6.1.2
13 silly saveTree   │ ├─┬ babel-core@6.26.0
13 silly saveTree   │ │ ├─┬ babel-code-frame@6.26.0
13 silly saveTree   │ │ │ ├── chalk@1.1.3
13 silly saveTree   │ │ │ └── js-tokens@3.0.2
13 silly saveTree   │ │ ├─┬ babel-generator@6.26.0
13 silly saveTree   │ │ │ ├─┬ babel-runtime@6.26.0
13 silly saveTree   │ │ │ │ ├── core-js@2.5.1
13 silly saveTree   │ │ │ │ └── regenerator-runtime@0.11.0
13 silly saveTree   │ │ │ ├─┬ babel-types@6.26.0
13 silly saveTree   │ │ │ │ └── lodash@4.17.4
13 silly saveTree   │ │ │ ├─┬ detect-indent@4.0.0
13 silly saveTree   │ │ │ │ └── repeating@2.0.1
13 silly saveTree   │ │ │ ├── jsesc@1.3.0
13 silly saveTree   │ │ │ └── lodash@4.17.4
13 silly saveTree   │ │ ├── babel-helpers@6.24.1
13 silly saveTree   │ │ ├─┬ babel-register@6.26.0
13 silly saveTree   │ │ │ ├── home-or-tmp@2.0.0
13 silly saveTree   │ │ │ └── source-map-support@0.4.18
13 silly saveTree   │ │ ├── babel-runtime@6.26.0
13 silly saveTree   │ │ ├─┬ babel-template@6.26.0
13 silly saveTree   │ │ │ ├─┬ babel-traverse@6.26.0
13 silly saveTree   │ │ │ │ ├── babylon@6.18.0
13 silly saveTree   │ │ │ │ └── globals@9.18.0
13 silly saveTree   │ │ │ └── babylon@6.18.0
13 silly saveTree   │ │ ├── babel-traverse@6.26.0
13 silly saveTree   │ │ ├── babel-types@6.26.0
13 silly saveTree   │ │ ├── babylon@6.18.0
13 silly saveTree   │ │ ├── json5@0.5.1
13 silly saveTree   │ │ ├── lodash@4.17.4
13 silly saveTree   │ │ └── minimatch@3.0.4
13 silly saveTree   │ ├── broccoli-funnel@1.2.0
13 silly saveTree   │ ├── broccoli-merge-trees@1.2.4
13 silly saveTree   │ ├─┬ broccoli-persistent-filter@1.4.3
13 silly saveTree   │ │ └── rsvp@3.6.2
13 silly saveTree   │ └── rsvp@3.6.2
13 silly saveTree   ├── broccoli-brocfile-loader@0.18.0
13 silly saveTree   ├── broccoli-builder@0.18.8
13 silly saveTree   ├─┬ broccoli-concat@3.2.2
13 silly saveTree   │ ├─┬ broccoli-stew@1.5.0
13 silly saveTree   │ │ ├─┬ broccoli-debug@0.6.2
13 silly saveTree   │ │ │ └── minimatch@3.0.4
13 silly saveTree   │ │ └── minimatch@3.0.4
13 silly saveTree   │ └── fs-extra@1.0.0
13 silly saveTree   ├── broccoli-config-loader@1.0.1
13 silly saveTree   ├─┬ broccoli-config-replace@1.1.2
13 silly saveTree   │ └── fs-extra@0.24.0
13 silly saveTree   ├── broccoli-debug@0.6.3
13 silly saveTree   ├── broccoli-funnel-reducer@1.0.0
13 silly saveTree   ├── broccoli-funnel@2.0.1
13 silly saveTree   ├── broccoli-merge-trees@2.0.0
13 silly saveTree   ├── broccoli-middleware@1.0.0
13 silly saveTree   ├── broccoli-source@1.1.0
13 silly saveTree   ├── broccoli-stew@1.5.0
13 silly saveTree   ├── calculate-cache-key-for-tree@1.1.0
13 silly saveTree   ├── capture-exit@1.2.0
13 silly saveTree   ├─┬ chalk@2.3.0
13 silly saveTree   │ ├─┬ ansi-styles@3.2.0
13 silly saveTree   │ │ └─┬ color-convert@1.9.0
13 silly saveTree   │ │   └── color-name@1.1.3
13 silly saveTree   │ └─┬ supports-color@4.5.0
13 silly saveTree   │   └── has-flag@2.0.0
13 silly saveTree   ├── clean-base-url@1.0.0
13 silly saveTree   ├─┬ compression@1.7.0
13 silly saveTree   │ ├── accepts@1.3.3
13 silly saveTree   │ ├── bytes@2.5.0
13 silly saveTree   │ ├─┬ compressible@2.0.11
13 silly saveTree   │ │ └── mime-db@1.29.0
13 silly saveTree   │ └── safe-buffer@5.1.1
13 silly saveTree   ├─┬ configstore@3.1.1
13 silly saveTree   │ └── dot-prop@4.2.0
13 silly saveTree   ├─┬ console-ui@2.0.1
13 silly saveTree   │ ├─┬ inquirer@2.0.0
13 silly saveTree   │ │ ├── ansi-escapes@1.4.0
13 silly saveTree   │ │ ├── chalk@1.1.3
13 silly saveTree   │ │ ├── cli-cursor@1.0.2
13 silly saveTree   │ │ ├── cli-width@2.1.0
13 silly saveTree   │ │ ├── figures@2.0.0
13 silly saveTree   │ │ └─┬ string-width@2.1.1
13 silly saveTree   │ │   ├── is-fullwidth-code-point@2.0.0
13 silly saveTree   │ │   └─┬ strip-ansi@4.0.0
13 silly saveTree   │ │     └── ansi-regex@3.0.0
13 silly saveTree   │ └─┬ ora@1.3.0
13 silly saveTree   │   ├── chalk@1.1.3
13 silly saveTree   │   ├─┬ cli-cursor@2.1.0
13 silly saveTree   │   │ └─┬ restore-cursor@2.0.0
13 silly saveTree   │   │   └── onetime@2.0.1
13 silly saveTree   │   └── cli-spinners@1.1.0
13 silly saveTree   ├── core-object@3.1.5
13 silly saveTree   ├── dag-map@2.0.2
13 silly saveTree   ├── diff@3.3.0
13 silly saveTree   ├── ember-cli-lodash-subset@2.0.1
13 silly saveTree   ├─┬ execa@0.8.0
13 silly saveTree   │ └── cross-spawn@5.1.0
13 silly saveTree   ├── find-up@2.1.0
13 silly saveTree   ├─┬ fs-extra@4.0.2
13 silly saveTree   │ └── jsonfile@4.0.0
13 silly saveTree   ├── glob@7.1.1
13 silly saveTree   ├── is-git-url@1.0.0
13 silly saveTree   ├─┬ lodash.template@4.4.0
13 silly saveTree   │ └── lodash.templatesettings@4.1.0
13 silly saveTree   ├── minimatch@3.0.4
13 silly saveTree   └── rsvp@3.6.2
14 verbose stack Error: Command failed: /usr/bin/git checkout 13d1672ac6d8ec446720b110e18956befdad1823
14 verbose stack fatal: reference is not a tree: 13d1672ac6d8ec446720b110e18956befdad1823
14 verbose stack
14 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose cwd /Users/bryan/Projects/sc-pp-frontend
16 verbose Darwin 17.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save-dev" "phantomjs-prebuilt@2.1.14"
18 verbose node v8.9.1
19 verbose npm  v5.6.0
20 error code 128
21 error Command failed: /usr/bin/git checkout 13d1672ac6d8ec446720b110e18956befdad1823
21 error fatal: reference is not a tree: 13d1672ac6d8ec446720b110e18956befdad1823
22 verbose exit [ 1, true ]

**Comment by BryanCrotaz** [comment]
Unrelated to Phantom. Closing.
