### ISSUE TITLE
Install failed with npm 

### ISSUE THREAD

**Issue by sengatang** [Medium/phantomjs#786]
```

> phantomjs-prebuilt@2.1.16 install /Users/tangsijia/华东师范大学/论文/项目/trail/newtest/crawler/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip
Saving to /var/folders/fn/fc3rqprx2tb1nh21hpqd2ybh0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...

Error making request.
Error: connect ETIMEDOUT 52.216.18.144:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tangsijia/.npm/_logs/2018-03-20T07_27_16_416Z-debug.log
```

**Comment by jbryson3** [comment]
This issue just cleared up for us

**Comment by faridiqbal** [comment]
I'm facing the same issue

**Comment by SynZhang** [comment]
I had the same problem，try `yarn global add phantomjs-prebuilt`.

**Comment by hongmaoxiao** [comment]
the same, why this happen
