### ISSUE TITLE
Getting error while installing phantomjs

### ISSUE THREAD

**Issue by Rakeshdrupal** [Medium/phantomjs#789]
Error checking path, continuing { Error: Cannot find module '/usr/lib/node_modules/phantomjs/lib/location'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at getLocationInLibModuleIfMatching (/usr/lib/node_modules/phantomjs/install.js:332:19)
    at Promise._successFn (/usr/lib/node_modules/phantomjs/install.js:389:28)
    at nextTickCallback (/usr/lib/node_modules/phantomjs/node_modules/kew/kew.js:47:28)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'MODULE_NOT_FOUND' }
/usr/lib/node_modules/phantomjs/phantomjs is not writable: EACCES: permission denied, mkdir '/usr/lib/node_modules/phantomjs/phantomjs'
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Using proxy http://registry.npmjs.org/
Receiving...

Error making request.
Error: tunneling socket could not be established, statusCode=500
    at ClientRequest.onConnect (/usr/lib/node_modules/phantomjs/node_modules/tunnel-agent/index.js:165:19)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at Socket.socketOnData (_http_client.js:472:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@2.1.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by DanielRuf** [comment]
Probably an issue with some proxy setup on your machine, antivirus or permission issues.
