### ISSUE TITLE
PhantomJS not found on PATH

### ISSUE THREAD

**Issue by vineet-agrawal96** [Medium/phantomjs#799]
npm install

> phantomjs-prebuilt@2.1.16 install D:\17May-Bixex\www-3\node_modules\phantomjs-
prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantom
js-2.1.1-windows.zip
Saving to C:\Users\dell\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip

Receiving...

Error making request.
Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed.
 You must install peer dependencies yourself.
npm WARN bootstrap@4.0.0 requires a peer of popper.js@^1.12.9 but none is instal
led. You must install peer dependencies yourself.
npm WARN halogen@0.2.0 requires a peer of react@^0.14.8 but none is installed. Y
ou must install peer dependencies yourself.
npm WARN halogen@0.2.0 requires a peer of react-dom@^0.14.8 but none is installe
d. You must install peer dependencies yourself.
npm WARN react-bootstrap-date-picker@5.1.0 requires a peer of react-bootstrap@^0
.31.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-bootstrap-datetimerangepicker@2.0.4 requires a peer of bootstrap-
daterangepicker@^2.1.19 but none is installed. You must install peer dependencie
s yourself.
npm WARN react-google-login@3.0.10 requires a peer of react@^16.0.0 but none is
installed. You must install peer dependencies yourself.
npm WARN react-google-login@3.0.10 requires a peer of react-dom@^16.0.0 but none
 is installed. You must install peer dependencies yourself.
npm WARN react-input-validation@1.0.4 requires a peer of react@^0.14.0 but none
is installed. You must install peer dependencies yourself.
npm WARN react-instagram-login@1.2.0 requires a peer of react@^16.0.0 but none i
s installed. You must install peer dependencies yourself.
npm WARN react-paginate@5.2.1 requires a peer of react@^16.0.0 but none is insta
lled. You must install peer dependencies yourself.
npm WARN react-render-html@0.6.0 requires a peer of react@^16.1.0 but none is in
stalled. You must install peer dependencies yourself.
npm WARN The package webpack is included as both a dev and production dependency
.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Roaming\npm-cache\_logs\2018-05-30T05_17_25_9
42Z-debug.log

**Comment by RoopaVenkatesh** [comment]
I am facing the same issue even after setting 

> npm set strict-ssl false



PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-windows.zip
Saving to C:\Users\rovenka\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...

Error making request.
Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TLSWrap.onread (net.js:618:25)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN microcks@0.0.1 No repository field.
npm WARN microcks@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.20 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rovenka\AppData\Roaming\npm-cache\_logs\2018-05-31T04_54_35_073Z-debug.log
