### ISSUE TITLE
PhantomJS not found on PATH

### ISSUE THREAD

**Issue by zhouLion** [Medium/phantomjs#808]
PhantomJS not found on PATH

the following is the error log
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to C:\Users\zq\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...
  [==--------------------------------------] 4%
Error making request.
Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:615:25)

**Comment by PoonamKalyani** [comment]
facing the same error:

Error making request.
Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TLSWrap.onread (net.js:618:25)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\NET1\AppData\Roaming\npm-cache\_logs\2018-08-08T08_25_25_071Z-debug.log

**Comment by mahaina** [comment]
same error

**Comment by mahaina** [comment]
same error:

> phantomjs-prebuilt@2.1.16 install /Users/baidu/Documents/GitProjects/baidu/ebiz/fe-cop-editor/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip
Saving to /var/folders/72/byjy11cs0dj_z3rjtxnj_nn00000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...

Error making request.
Error: connect ETIMEDOUT 54.231.50.26:443
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

Please report this full log at https://github.com/Medium/phantomjs

**Comment by zhouLion** [comment]
## This is becuase of the great firewall.
# I resovled it yesterday.Following is my suggestion:
- 1.download phantomjs zip file manually from [here](https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip)
- 2.unzip the zip file to your disk path as you want
- 3.set EnvironmentVariable,add 'PhantomJS' to your PATH

**Comment by progay** [comment]
same error:

`
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TLSWrap.onread (net.js:618:25)
`

**Comment by nickboldt** [comment]
More of the same error:

`     [exec] > phantomjs@2.1.7 install /tmp/eclipse-che-6.9/dashboard/node_modules/phantomjs
     [exec] > node install.js
     [exec] 
     [exec] PhantomJS not found on PATH
     [exec] Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-linux-x86_64.tar.bz2
     [exec] Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
     [exec] Using proxy http://build_eclipse-che-6-9_20180820.2342%2Btracking:******@indy-proxy.project-newcastle.svc.cluster.local:80/
     [exec] Receiving...
     [exec] Error making request.
     [exec] Error: tunneling socket could not be established, cause=socket hang up
     [exec]     at ClientRequest.onError (/tmp/eclipse-che-6.9/dashboard/node_modules/phantomjs/node_modules/tunnel-agent/index.js:176:17)
     [exec]     at ClientRequest.g (events.js:292:16)
     [exec]     at emitOne (events.js:96:13)
     [exec]     at ClientRequest.emit (events.js:188:7)
     [exec]     at Socket.socketOnEnd (_http_client.js:346:9)
     [exec]     at emitNone (events.js:91:20)
     [exec]     at Socket.emit (events.js:185:7)
     [exec]     at endReadableNT (_stream_readable.js:974:12)
     [exec]     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     [exec]     at process._tickCallback (internal/process/next_tick.js:104:9)
     [exec] 
     [exec] Please report this full log at https://github.com/Medium/phantomjs
     [exec] npm verb lifecycle phantomjs@2.1.7~install: unsafe-perm in lifecycle true
     [exec] npm verb lifecycle phantomjs@2.1.7~install: PATH: /opt/rh/rh-nodejs6/root/usr/lib/node_modules/npm/bin/node-gyp-bin:/tmp/eclipse-che-6.9/dashboard/node_modules/phantomjs/node_modules/.bin:/tmp/eclipse-che-6.9/dashboard/node_modules/.bin:/opt/rh/rh-nodejs6/root/usr/bin:/opt/app-root/src/node_modules/.bin/:/opt/app-root/src/.npm-global/bin/:/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
     [exec] npm verb lifecycle phantomjs@2.1.7~install: CWD: /tmp/eclipse-che-6.9/dashboard/node_modules/phantomjs
     [exec] npm info lifecycle phantomjs@2.1.7~install: Failed to exec install script
     [exec] npm verb unlock done using /home/worker/.npm/_locks/staging-049da445a61ee92c.lock for /tmp/eclipse-che-6.9/dashboard/node_modules/.staging
     [exec] 
     [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
     [exec] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
     [exec] npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
     [exec] npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
     [exec] npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
     [exec] npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
     [exec] npm verb stack Error: phantomjs@2.1.7 install: `node install.js`
     [exec] npm verb stack Exit status 1
     [exec] npm verb stack     at EventEmitter.<anonymous> (/opt/rh/rh-nodejs6/root/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
     [exec] npm verb stack     at emitTwo (events.js:106:13)
     [exec] npm verb stack     at EventEmitter.emit (events.js:191:7)
     [exec] npm verb stack     at ChildProcess.<anonymous> (/opt/rh/rh-nodejs6/root/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
     [exec] npm verb stack     at emitTwo (events.js:106:13)
     [exec] npm verb stack     at ChildProcess.emit (events.js:191:7)
     [exec] npm verb stack     at maybeClose (internal/child_process.js:920:16)
     [exec] npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
     [exec] npm verb pkgid phantomjs@2.1.7
     [exec] npm verb cwd /tmp/eclipse-che-6.9/dashboard
     [exec] npm ERR! Linux 3.10.0-693.11.6.el7.x86_64
     [exec] npm ERR! argv "/opt/rh/rh-nodejs6/root/usr/bin/node" "/opt/rh/rh-nodejs6/root/usr/bin/npm" "install"
     [exec] npm ERR! node v6.11.3
     [exec] npm ERR! npm  v3.10.9
     [exec] npm ERR! code ELIFECYCLE
     [exec] 
     [exec] npm ERR! phantomjs@2.1.7 install: `node install.js`
     [exec] npm ERR! Exit status 1
     [exec] npm ERR! 
     [exec] npm ERR! Failed at the phantomjs@2.1.7 install script 'node install.js'.
     [exec] npm ERR! Make sure you have the latest version of node.js and npm installed.
     [exec] npm ERR! If you do, this is most likely a problem with the phantomjs package,
     [exec] npm ERR! not with npm itself.
     [exec] npm ERR! Tell the author that this fails on your system:
     [exec] npm ERR!     node install.js
     [exec] npm ERR! You can get information on how to open an issue for this project with:
     [exec] npm ERR!     npm bugs phantomjs
     [exec] npm ERR! Or if that isn't available, you can get their info via:
     [exec] npm ERR!     npm owner ls phantomjs
     [exec] npm ERR! There is likely additional logging output above.
     [exec] npm verb exit [ 1, true ]`

**Comment by nickboldt** [comment]
Workaround that worked for me - basically the problem is I can't resolve stuff through proxy over https, so I had to copy the tarball to an http host, then manually download it thru the proxy w/ wget, and install it manually from the /tmp folder:

https://gist.github.com/nickboldt/fd99ff0649304297acf98d1d2aaace06
