### ISSUE TITLE
phantom js not found in path

### ISSUE THREAD

**Issue by mrekha** [Medium/phantomjs#814]
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip
Saving to /var/folders/3m/2ssd1sx13v1183r8jyymnkzhfhb75m/T/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...

Error making request.
Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)

**Comment by bllevy** [comment]
Running into the same issue, seems to be related #815
