### ISSUE TITLE
 Error: tunneling socket could not be established, cause=Parse Error

### ISSUE THREAD

**Issue by rajeevsuryavanshi85** [Medium/phantomjs#815]
[INFO] > phantomjs@1.9.20 install /home/jenkins/jenkins2/workspace/gatekeeper-ear-builder-trunk/gatekeeper-ui-war/src/main/webapp_src/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
[INFO] > node install.js
[INFO] 
[INFO] PhantomJS not found on PATH
[INFO] Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-linux-x86_64.tar.bz2
[INFO] Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
[INFO] Using proxy http://Proxy_WAS:******@tstproxy.testbbh.com:9090/
[INFO] Receiving...
[INFO] 
[ERROR] Error making request.
[ERROR] Error: tunneling socket could not be established, cause=Parse Error
[ERROR]     at ClientRequest.onError (/home/jenkins/jenkins2/workspace/gatekeeper-ear-builder-trunk/gatekeeper-ui-war/src/main/webapp_src/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/node_modules/request/node_modules/tunnel-agent/index.js:176:17)
[ERROR]     at ClientRequest.g (events.js:199:16)
[ERROR]     at ClientRequest.emit (events.js:107:17)
[ERROR]     at Socket.socketOnData (_http_client.js:322:9)
[ERROR]     at Socket.emit (events.js:107:17)
[ERROR]     at readableAddChunk (_stream_readable.js:163:16)
[ERROR]     at Socket.Readable.push (_stream_readable.js:126:10)
[ERROR]     at TCP.onread (net.js:540:20)
[ERROR] 
[ERROR] Please report this full log at https://github.com/Medium/phantomjs
[ERROR] npm ERR! Linux 3.10.0-862.11.6.el7.x86_64
[ERROR] npm ERR! argv "/home/jenkins/jenkins2/workspace/gatekeeper-ear-builder-trunk/gatekeeper-ui-war/target/node/node" "/home/jenkins/jenkins2/workspace/gatekeeper-ear-builder-trunk/gatekeeper-ui-war/target/node/node_modules/npm/bin/npm-cli.js" "install" "--https-proxy=http://Proxy_WAS:HTML2006@tstproxy.testbbh.com:9090" "--proxy=http://Proxy_WAS:HTML2006@tstproxy.testbbh.com:9090"
[ERROR] npm ERR! node v0.12.18
[ERROR] npm ERR! npm  v2.15.11
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] 
[ERROR] npm ERR! phantomjs@1.9.20 install: `node install.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
[ERROR] npm ERR! This is most likely a problem with the phantomjs package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node install.js
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs phantomjs
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR! 
[ERROR] npm ERR!     npm owner ls phantomjs
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/jenkins/jenkins2/workspace/gatekeeper-ear-builder-trunk/gatekeeper-ui-war/src/main/webapp_src/npm-debug.log

**Comment by bllevy** [comment]
```sh
> phantomjs-prebuilt@2.1.15 install /usr/src/app/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Received 118K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  killed: false,
  code: 2,
  signal: null,
  cmd: 'tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2' } Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

I'm also running into issues with the phantomjs-prebuilt download today.

```sh
npm ERR! Linux 4.9.93-linuxkit-aufs
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.15 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1
```
